(** * BB(8) champion-rule machine with a 35-digit start: 1RB0RA_1LC1LF_1RD0LB_1RA1LE_---0LC_1RG1LD_1LC0RH_1RG1LF halts *)

(** Generated by bb8_list/investigations/bb8_champ35_1RB0RA_1LC0RH (gen35.py, planner8.py).
    The machine follows the BB(7) champion's recursion (Ligocki's B(a; b1..bk) counter).
    Family (head in G on a blank, nothing to the right), digits nearest-first in [ds]:
      Kc ds a b = 0^inf 1 .. (01)^(3 d_2 + 1) 1 (01)^(3 d_1 + 1) 1 (01)^(3a+1) 1 (01)^(3b+1) 1 (01)^2 G> 0^inf
    Rules (all parameters): R1 K ds (S a) b -> K ds a (2b+2);  R2 K (S y :: t) 0 b -> K (y :: t) (2b+2) 0;
    R3 K (0^(k+1) ++ S y :: t) 0 b -> K (0^k ++ (2b+2) :: y :: t) 0 0;  R4 K (0^(k+1)) 0 b halts. *)

From BB8 Require Import Individual82.
From Coq Require Import Lia PeanoNat List Wf_nat Wellfounded.Inverse_Image.
Import ListNotations.
Set Default Goal Selector "!".

(* machine: 1RB0RA_1LC1LF_1RD0LB_1RA1LE_---0LC_1RG1LD_1LC0RH_1RG1LF *)
Definition tm : TM := fun '(q, s) =>
  match q, s with
  | A, 0 => Some (1, R, B)  | A, 1 => Some (0, R, A)
  | B, 0 => Some (1, L, C)  | B, 1 => Some (1, L, F)
  | C, 0 => Some (1, R, D)  | C, 1 => Some (0, L, B)
  | D, 0 => Some (1, R, A)  | D, 1 => Some (1, L, E)
  | E, 0 => None            | E, 1 => Some (0, L, C)
  | F, 0 => Some (1, R, G)  | F, 1 => Some (1, L, D)
  | G, 0 => Some (1, L, C)  | G, 1 => Some (0, R, H)
  | H, 0 => Some (1, R, G)  | H, 1 => Some (1, L, F)
  end.

Notation "c --> c'" := (c -[ tm ]-> c')   (at level 40).
Notation "c -->* c'" := (c -[ tm ]->* c') (at level 40).
Notation "c -->+ c'" := (c -[ tm ]->+ c') (at level 40).

(** ** Tape normalization (as in BB7_16582_1RB1LD.v) *)

Lemma align_lpow : forall (x : Sym) xs ys n,
  (x::xs)^^n *> x >> ys = x >> (xs ++ [x])^^n *> ys.
Proof.
  induction n.
  - reflexivity.
  - simpl. repeat rewrite Str_app_assoc. rewrite IHn. reflexivity.
Qed.

Lemma align_lpow_const : forall (x : Sym) xs n,
  (x::xs)^^n *> const x = x >> (xs ++ [x])^^n *> const x.
Proof. intros. rewrite const_unfold at 1. apply align_lpow. Qed.

Ltac align_tape := repeat ((rewrite align_lpow || rewrite align_lpow_const); simpl app).
Ltac norm_nat := repeat progress (rewrite ?Nat.add_succ_r, ?Nat.add_0_r; simpl).
Ltac finish_norm := apply evstep_refl'; norm_nat; align_tape; try reflexivity; lia_refl.

(** crossings *)
Lemma cr_AR_101_001 : forall n l r, l {{A}}> [1;0;1]^^n *> r -->* [0;0;1]^^n *> l {{A}}> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cr_BL_001_001 : forall n l r, [0;0;1]^^n *> l <{{B}} r -->* l <{{B}} [0;0;1]^^n *> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cr_BL_01_01 : forall n l r, [0;1]^^n *> l <{{B}} r -->* l <{{B}} [0;1]^^n *> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cr_CL_10_10 : forall n l r, [1;0]^^n *> l <{{C}} r -->* l <{{C}} [1;0]^^n *> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cr_GR_10_10 : forall n l r, l {{G}}> [1;0]^^n *> r -->* [1;0]^^n *> l {{G}}> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cr_HR_01_01 : forall n l r, l {{H}}> [0;1]^^n *> r -->* [0;1]^^n *> l {{H}}> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cx_AR_01_01_c0 : forall n l r, 0 >> l {{A}}> [0;1]^^n *> r -->* 0 >> [0;1]^^n *> l {{A}}> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cx_BL_110_101_c0101010101010100 : forall n l r, [1;1;0]^^n *> l <{{B}} 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 0 >> r -->* l <{{B}} 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 0 >> [1;0;1]^^n *> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cx_BR_10_01_c10 : forall n l r, 1 >> 0 >> l {{B}}> [1;0]^^n *> r -->* 1 >> 0 >> [0;1]^^n *> l {{B}}> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cx_DL_011_101_c110101010101010100 : forall n l r, [0;1;1]^^n *> l <{{D}} 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 0 >> r -->* l <{{D}} 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 0 >> [1;0;1]^^n *> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cx_FL_101_101_c10101010101010100 : forall n l r, [1;0;1]^^n *> l <{{F}} 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 0 >> r -->* l <{{F}} 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 0 >> [1;0;1]^^n *> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cx_HR_001_101_c0110 : forall n l r, 0 >> 1 >> 1 >> 0 >> l {{H}}> [0;0;1]^^n *> r -->* 0 >> 1 >> 1 >> 0 >> [1;0;1]^^n *> l {{H}}> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cx_HR_101_101_c0 : forall n l r, 0 >> l {{H}}> [1;0;1]^^n *> r -->* 0 >> [1;0;1]^^n *> l {{H}}> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

(** phases *)
Lemma ROUND : forall N T l, ([1;0]^^(T) *> 1 >> 1 >> 0 >> [1;0]^^(N) *> 1 >> l) {{G}}> (const 0) -->+ (1 >> 0 >> 1 >> 0 >> [1;0]^^(T) *> 1 >> [1;0]^^(N) *> 1 >> l) {{G}}> (const 0).
Proof.
  intros.
  eapply progress_intro; [prove_step | simpl_tape]. follow cr_CL_10_10. do 5 step.
  follow cr_GR_10_10. do 2 step. finish_norm.
Qed.

Lemma R1F : forall A T l, (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> [1;0]^^(T) *> 1 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> [1;0]^^(A) *> 1 >> l) {{G}}> (const 0) -->+ (1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> [1;0]^^(T) *> 1 >> [1;0]^^(A) *> 1 >> l) {{G}}> (const 0).
Proof.
  intros.
  eapply progress_intro; [prove_step | simpl_tape]. do 8 step. follow cr_CL_10_10. do 7 step.
  follow cx_BR_10_01_c10. do 45 step. follow cr_BL_01_01. do 7 step. follow cr_HR_01_01. do 19 step.
  follow cr_BL_01_01. do 11 step. follow cr_HR_01_01. do 16 step. finish_norm.
Qed.

Lemma R2F : forall T X l, (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> [1;0]^^(T) *> 1 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> [1;0]^^(X) *> 1 >> l) {{G}}> (const 0) -->+ (1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> [1;0]^^(T) *> 1 >> [1;0]^^(X) *> 1 >> l) {{G}}> (const 0).
Proof.
  intros.
  eapply progress_intro; [prove_step | simpl_tape]. do 8 step. follow cr_CL_10_10. do 7 step.
  follow cx_BR_10_01_c10. do 45 step. follow cr_BL_01_01. do 13 step. follow cx_AR_01_01_c0.
  do 38 step. follow cr_BL_01_01. do 11 step. follow cr_HR_01_01. do 15 step. follow cr_BL_01_01.
  do 15 step. follow cr_HR_01_01. do 19 step. finish_norm.
Qed.

Lemma E3 : forall M T l, ([1;0]^^(T) *> 1 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^(M) *> l) {{G}}> (const 0) -->+ ([1;0]^^(T) *> 1 >> 0 >> 1 >> 1 >> [1;0;1]^^(M) *> l) <{{C}} (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> const 0).
Proof.
  intros.
  eapply progress_intro; [prove_step | simpl_tape]. follow cr_CL_10_10. do 7 step.
  follow cx_BR_10_01_c10. do 13 step. follow cr_BL_01_01. do 13 step. follow cx_AR_01_01_c0.
  do 4 step. rewrite (align_lpow 0 [1] _ T). simpl app. do 3 step. finish_norm.
Qed.

Lemma HOP : forall M T j l, ([1;0]^^(T) *> 1 >> 0 >> 1 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^(M) *> l) <{{C}} (0 >> 1 >> 0 >> 1 >> [1;0;1]^^(j) *> 0 >> const 0) -->* ([1;0]^^(T) *> 1 >> 0 >> 1 >> 1 >> [1;0;1]^^(M) *> l) <{{C}} (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^(j) *> 0 >> const 0).
Proof.
  intros.
  follow cr_CL_10_10. do 15 step. follow cx_BR_10_01_c10. do 3 step.
  rewrite (align_lpow 0 [1] _ T). simpl app. do 3 step. finish_norm.
Qed.

Lemma X3 : forall J T X l, ([1;0]^^(T) *> 1 >> 0 >> 1 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> [1;0]^^(X) *> 1 >> l) <{{C}} (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^(J) *> 0 >> const 0) -->* (1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^(J) *> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> [1;0]^^(T) *> 1 >> [1;0]^^(X) *> 1 >> l) {{G}}> (const 0).
Proof.
  intros.
  follow cr_CL_10_10. do 15 step. follow cx_BR_10_01_c10. do 3 step.
  rewrite (align_lpow 0 [1] _ T). simpl app. do 3 step. follow cr_CL_10_10. do 9 step.
  follow cr_GR_10_10. do 1 step. follow cr_CL_10_10. do 13 step. follow cr_GR_10_10. do 16 step.
  follow cx_HR_101_101_c0. do 1 step. finish_norm.
Qed.

Lemma X4 : forall J T, ([1;0]^^(T) *> 1 >> 0 >> 1 >> 1 >> const 0) <{{C}} (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^(J) *> 0 >> const 0) -->* ([0;1]^^(T) *> 1 >> 1 >> const 0) <{{C}} (1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 0 >> 1 >> 0 >> 0 >> 1 >> [0;0;1]^^(J) *> 0 >> 1 >> 0 >> const 0).
Proof.
  intros.
  follow cr_CL_10_10. do 9 step. follow cr_GR_10_10. do 1 step. follow cr_CL_10_10. do 25 step.
  follow cx_BR_10_01_c10. do 19 step. follow cr_AR_101_001. do 3 step. follow cr_BL_001_001.
  do 15 step. follow cr_BL_01_01. do 21 step. follow cx_AR_01_01_c0. do 4 step.
  rewrite (align_lpow 0 [1] _ T). simpl app. do 3 step. follow cr_CL_10_10. do 25 step.
  follow cx_BR_10_01_c10. do 3 step. rewrite (align_lpow 0 [1] _ T). simpl app. do 3 step.
  follow cr_CL_10_10. do 15 step. follow cx_BR_10_01_c10. do 3 step.
  rewrite (align_lpow 0 [1] _ T). simpl app. do 3 step. follow cr_CL_10_10. do 17 step.
  follow cx_BR_10_01_c10. do 3 step. rewrite (align_lpow 0 [1] _ T). simpl app. do 3 step.
  follow cr_CL_10_10. do 7 step. follow cx_BR_10_01_c10. do 3 step.
  rewrite (align_lpow 0 [1] _ T). simpl app. do 3 step. follow cr_CL_10_10. do 9 step.
  follow cx_BR_10_01_c10. do 3 step. finish_norm.
Qed.

Lemma TLP : forall J T t, (0 >> 1 >> [0;1]^^(T) *> 1 >> 1 >> const 0) <{{C}} ([1;0;1]^^(t) *> 1 >> 0 >> 0 >> 1 >> 0 >> 0 >> 1 >> [0;0;1]^^(J) *> 0 >> 1 >> 0 >> const 0) -->+ ([0;1]^^(T) *> 1 >> 1 >> const 0) <{{C}} (1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^(t) *> 1 >> 0 >> 0 >> 1 >> 0 >> 0 >> 1 >> [0;0;1]^^(J) *> 0 >> 1 >> 0 >> const 0).
Proof.
  intros.
  eapply progress_intro; [prove_step | simpl_tape]. rewrite (align_lpow 1 [0;1] _ t). simpl app.
  do 3 step. follow cr_BL_01_01. do 5 step. follow cx_AR_01_01_c0. do 4 step.
  rewrite (align_lpow 0 [1] _ T). simpl app. do 3 step. follow cr_CL_10_10. do 9 step.
  follow cx_BR_10_01_c10. do 3 step. finish_norm.
Qed.

Lemma FIN : forall J t, exists c, (1 >> 1 >> const 0) <{{C}} (1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^(t) *> 1 >> 0 >> 0 >> 1 >> 0 >> 0 >> 1 >> [0;0;1]^^(J) *> 0 >> 1 >> 0 >> const 0) -->* c /\ halted tm c.
Proof.
  intros. eexists. split.
  - do 28 step. follow cx_HR_101_101_c0. do 8 step. rewrite (align_lpow 1 [0;1] _ t). simpl app.
  do 1 step. rewrite (align_lpow 0 [1;1] _ t). simpl app. do 24 step. follow cx_HR_001_101_c0110.
  do 29 step. rewrite (align_lpow 1 [0;1] _ J). simpl app. do 1 step.
  rewrite (align_lpow 0 [1;1] _ J). simpl app. do 27 step.
  rewrite (align_lpow 1 [1;0] _ J). simpl app. do 1 step.
  rewrite (align_lpow 1 [0;1] _ J). simpl app. do 1 step.
  rewrite (align_lpow 0 [1;1] _ J). simpl app. do 67 step. follow cx_BL_110_101_c0101010101010100.
  do 1 step. rewrite (align_lpow 1 [1;0] _ t). simpl app. do 1 step.
  rewrite (align_lpow 1 [0;1] _ t). simpl app. do 1 step.
  rewrite (align_lpow 0 [1;1] _ t). simpl app. apply evstep_refl.
  - simpl. reflexivity.
Qed.

(** ** The digit family *)

Fixpoint lft (ds : list nat) : side :=
  match ds with
  | [] => const 0
  | d :: t => [1;0]^^(S (3 * d)) *> 1 >> lft t
  end.

(** Kc ds a b = 0^inf 1 (01)^(3 d_n+1) 1 ... 1 (01)^(3 d_1+1) 1 (01)^(3a+1) 1 (01)^(3b+1) 1 (01)^2 G> 0^inf
    (ds nearest-first: d_1 is the digit next to the counters) *)
Definition Kc (ds : list nat) (a b : nat) : Q * tape :=
  ([1;0]^^(2) *> 1 >> [1;0]^^(S (3 * b)) *> 1 >> [1;0]^^(S (3 * a)) *> 1 >> lft ds) {{G}}> const 0.

Lemma lft_cons : forall d t, lft (d :: t) = [1;0]^^(S (3 * d)) *> 1 >> lft t.
Proof. reflexivity. Qed.

Lemma lft_zeros : forall k t, lft (repeat O k ++ t) = [1;0;1]^^k *> lft t.
Proof. induction k; intros. - reflexivity. - simpl. rewrite IHk. reflexivity. Qed.

Lemma lft_blank : forall k, lft (repeat O k) = [1;0;1]^^k *> const 0.
Proof. intros. rewrite <- (app_nil_r (repeat O k)), lft_zeros. reflexivity. Qed.

(** ** Rules *)

Lemma ROUNDS : forall n N T l,
  ([1;0]^^T *> 1 >> [1;0]^^(n + N) *> 1 >> l) {{G}}> const 0 -->*
  ([1;0]^^(2 * n + T) *> 1 >> [1;0]^^N *> 1 >> l) {{G}}> const 0.
Proof.
  induction n; intros.
  - finish.
  - eapply evstep_trans; [apply progress_evstep, (ROUND (n + N) T l) |].
    follow (IHn N (S (S T)) l).
    finish.
Qed.

Lemma R1 : forall ds a b, Kc ds (S a) b -->+ Kc ds a (2 * b + 2).
Proof.
  intros. unfold Kc.
  replace (S (3 * S a)) with (S (S (S (S (3 * a))))) by lia.
  replace (S (3 * (2 * b + 2))) with (S (S (S (S (S (S (S (6 * b)))))))) by lia.
  follow (ROUNDS (S (3 * b)) O 2 ([1;0]^^(S (S (S (S (3 * a))))) *> 1 >> lft ds)).
  replace (2 * S (3 * b) + 2) with (S (S (S (S (6 * b))))) by lia.
  apply (R1F (S (3 * a)) (6 * b) (lft ds)).
Qed.

Lemma R2 : forall y t b, Kc (S y :: t) O b -->+ Kc (y :: t) (2 * b + 2) O.
Proof.
  intros. unfold Kc. rewrite lft_cons.
  replace (S (3 * S y)) with (S (S (S (S (3 * y))))) by lia.
  replace (S (3 * (2 * b + 2))) with (S (S (S (S (S (S (S (6 * b)))))))) by lia.
  follow (ROUNDS (S (3 * b)) O 2 ([1;0]^^(S (3 * O)) *> 1 >> [1;0]^^(S (S (S (S (3 * y))))) *> 1 >> lft t)).
  replace (2 * S (3 * b) + 2) with (S (S (S (S (6 * b))))) by lia.
  apply (R2F (6 * b) (S (3 * y)) (lft t)).
Qed.

Lemma HOPS : forall M j T l,
  ([1;0]^^T *> 1 >> 0 >> 1 >> 1 >> [1;0;1]^^M *> l) <{{C}} (0 >> 1 >> 0 >> 1 >> [1;0;1]^^j *> 0 >> const 0) -->*
  ([1;0]^^T *> 1 >> 0 >> 1 >> 1 >> l) <{{C}} (0 >> 1 >> 0 >> 1 >> [1;0;1]^^(j + M) *> 0 >> const 0).
Proof.
  induction M; intros.
  - finish.
  - follow (HOP M T j l).
    follow (IHM (S j) T l).
    finish.
Qed.

Lemma R3 : forall M y t b,
  Kc (repeat O (S M) ++ S y :: t) O b -->+ Kc (repeat O M ++ (2 * b + 2) :: y :: t) O O.
Proof.
  intros. unfold Kc. rewrite !lft_zeros, !lft_cons.
  replace (S (3 * S y)) with (S (S (S (S (3 * y))))) by lia.
  replace (S (3 * (2 * b + 2))) with (S (S (S (S (S (S (S (6 * b)))))))) by lia.
  follow (ROUNDS (S (3 * b)) O 2 ([1;0]^^(S (3 * O)) *> 1 >> [1;0;1]^^(S M) *> [1;0]^^(S (S (S (S (3 * y))))) *> 1 >> lft t)).
  replace (2 * S (3 * b) + 2) with (S (S (S (S (6 * b))))) by lia.
  eapply progress_evstep_trans; [apply (E3 M (S (S (S (S (6 * b))))) ([1;0]^^(S (S (S (S (3 * y))))) *> 1 >> lft t)) |].
  follow (HOPS M 1 (S (S (S (S (6 * b))))) ([1;0]^^(S (S (S (S (3 * y))))) *> 1 >> lft t)).
  follow (X3 M (S (S (S (S (6 * b))))) (S (3 * y)) (lft t)).
  finish.
Qed.

Lemma TLPS : forall T t J,
  ([0;1]^^T *> 1 >> 1 >> const 0) <{{C}} ([1;0;1]^^t *> 1 >> 0 >> 0 >> 1 >> 0 >> 0 >> 1 >> [0;0;1]^^J *> 0 >> 1 >> 0 >> const 0) -->*
  (1 >> 1 >> const 0) <{{C}} ([1;0;1]^^(2 * T + t) *> 1 >> 0 >> 0 >> 1 >> 0 >> 0 >> 1 >> [0;0;1]^^J *> 0 >> 1 >> 0 >> const 0).
Proof.
  induction T; intros.
  - finish.
  - eapply evstep_trans; [apply progress_evstep, (TLP J T t) |].
    follow (IHT (S (S t)) J).
    finish.
Qed.

Lemma R4 : forall M b, exists c, Kc (repeat O (S M)) O b -->* c /\ halted tm c.
Proof.
  intros. unfold Kc. rewrite lft_blank.
  destruct (FIN M (2 * S (S (S (S (6 * b)))) + 1)) as [c [H1 H2]].
  exists c. split; [| exact H2].
  follow (ROUNDS (S (3 * b)) O 2 ([1;0]^^(S (3 * O)) *> 1 >> [1;0;1]^^(S M) *> const 0)).
  replace (2 * S (3 * b) + 2) with (S (S (S (S (6 * b))))) by lia.
  eapply evstep_trans; [apply progress_evstep, (E3 M (S (S (S (S (6 * b))))) (const 0)) |].
  follow (HOPS M 1 (S (S (S (S (6 * b))))) (const 0)).
  follow (X4 M (S (S (S (S (6 * b)))))).
  follow (TLPS (S (S (S (S (6 * b))))) 6 M).
  replace (2 * S (S (S (S (6 * b)))) + 6) with (S (S (S (S (S (2 * S (S (S (S (6 * b)))) + 1)))))) by lia.
  exact H1.
Qed.

(** ** Abstract part: the digit list descends lexicographically *)

(** b -> 2b+2 applied a times (a rounds of R1). *)
Fixpoint dbl (a b : nat) : nat :=
  match a with
  | O => b
  | S a' => dbl a' (2 * b + 2)
  end.

Lemma R1ITER : forall a ds b, Kc ds a b -->* Kc ds O (dbl a b).
Proof.
  induction a; intros.
  - finish.
  - eapply evstep_trans; [apply progress_evstep, R1 |].
    apply IHa.
Qed.

(** Lexicographic order on lists of the same length (head = most significant). *)
Inductive lex : list nat -> list nat -> Prop :=
  | lex_hd : forall a b l l', a < b -> length l = length l' -> lex (a :: l) (b :: l')
  | lex_tl : forall a l l', lex l l' -> lex (a :: l) (a :: l').

Lemma lex_len : forall l l', lex l l' -> length l = length l'.
Proof. intros l l' H. induction H; simpl; f_equal; assumption. Qed.

Lemma lex_acc : forall n ds, length ds = n -> Acc lex ds.
Proof.
  induction n; intros ds Hl.
  - destruct ds; [| simpl in Hl; discriminate].
    constructor. intros y Hy. inversion Hy.
  - destruct ds as [| d r]; [simpl in Hl; discriminate |].
    simpl in Hl. injection Hl as Hl.
    revert r Hl.
    induction d as [d IHd] using lt_wf_ind. intros r Hl.
    assert (Hr : Acc lex r) by (apply IHn; exact Hl).
    revert Hl. induction Hr as [r _ IHr]. intros Hl.
    constructor. intros y Hy. inversion Hy; subst.
    + apply IHd; [assumption |]. lia.
    + apply IHr; [assumption |]. pose proof (lex_len _ _ H1). lia.
Qed.

Definition ltds (x y : list nat) : Prop := lex (rev x) (rev y).

Lemma ltds_acc : forall ds, Acc ltds ds.
Proof.
  intros ds. apply (Acc_inverse_image _ _ lex (@rev nat)).
  eapply lex_acc. reflexivity.
Qed.

Lemma lex_pre : forall p l l', lex l l' -> lex (p ++ l) (p ++ l').
Proof. induction p; intros; simpl; [assumption | apply lex_tl; apply IHp; assumption]. Qed.

Lemma rev_rep : forall k, rev (repeat O k) = repeat O k.
Proof.
  induction k; simpl; [reflexivity |].
  rewrite IHk. clear IHk. induction k; simpl; [reflexivity | rewrite IHk; reflexivity].
Qed.

Lemma len_rep : forall k, length (repeat O k) = k.
Proof. induction k; simpl; [reflexivity | f_equal; assumption]. Qed.

Lemma ltds_R2 : forall y t, ltds (y :: t) (S y :: t).
Proof.
  intros. unfold ltds. simpl.
  apply lex_pre. apply lex_hd; [lia | reflexivity].
Qed.

Lemma ltds_R3 : forall M y t x,
  ltds (repeat O M ++ x :: y :: t) (repeat O (S M) ++ S y :: t).
Proof.
  intros. unfold ltds.
  assert (E1 : rev (repeat O M ++ x :: y :: t) = rev t ++ y :: x :: repeat O M).
  { rewrite rev_app_distr, rev_rep. cbn [rev]. rewrite <- !app_assoc. reflexivity. }
  assert (E2 : rev (repeat O (S M) ++ S y :: t) = rev t ++ S y :: repeat O (S M)).
  { rewrite rev_app_distr, rev_rep. cbn [rev]. rewrite <- app_assoc. reflexivity. }
  rewrite E1, E2.
  apply lex_pre. apply lex_hd; [lia |]. simpl. rewrite len_rep. reflexivity.
Qed.

Lemma decomp : forall ds,
  (exists k, ds = repeat O k) \/ (exists k y t, ds = repeat O k ++ S y :: t).
Proof.
  induction ds as [| d r IH].
  - left. exists O. reflexivity.
  - destruct d.
    + destruct IH as [[k Hk] | [k [y [t Hk]]]].
      * left. exists (S k). simpl. rewrite Hk. reflexivity.
      * right. exists (S k), y, t. simpl. rewrite Hk. reflexivity.
    + right. exists O, d, r. reflexivity.
Qed.

(** Every nonempty list with a = 0 leads to a halt. *)
Theorem all_halt : forall ds, ds <> [] -> forall b,
  exists c, Kc ds O b -->* c /\ halted tm c.
Proof.
  intros ds. induction (ltds_acc ds) as [ds _ IH]. intros Hne b.
  destruct (decomp ds) as [[k Hk] | [k [y [t Hk]]]].
  - destruct k as [| M]; [subst; simpl in Hne; congruence |].
    subst. apply R4.
  - destruct k as [| M].
    + subst. simpl.
      destruct (IH (y :: t) (ltds_R2 y t) ltac:(discriminate) (dbl (2 * b + 2) O)) as [c [H1 H2]].
      exists c. split; [| exact H2].
      eapply evstep_trans; [apply progress_evstep, R2 |].
      eapply evstep_trans; [apply R1ITER |].
      exact H1.
    + subst.
      destruct (IH (repeat O M ++ (2 * b + 2) :: y :: t) (ltds_R3 M y t (2 * b + 2))
                   ltac:(destruct M; simpl; discriminate) O) as [c [H1 H2]].
      exists c. split; [| exact H2].
      eapply evstep_trans; [apply progress_evstep, R3 |].
      exact H1.
Qed.

(** ** The run from the blank tape *)

Lemma init_reach : c0 -->* Kc (repeat O 34 ++ [2]) O O.
Proof.
  unfold c0, Kc.
  do 6397 step.
  apply evstep_refl'. reflexivity.
Qed.

Theorem halt : halts tm c0.
Proof.
  destruct (all_halt (repeat O 34 ++ [2]) ltac:(discriminate) O) as [c [H1 H2]].
  assert (Hrun : c0 -->* c) by (follow init_reach; exact H1).
  destruct (with_counter Hrun) as [n Hn].
  eapply halts_multistep; [| exact Hn].
  apply halted_halts. exact H2.
Qed.

