(** * n1 in the fast-growing hierarchy, and Graham's number *)

(** Generated by bb8_list/investigations/bb10_n1_coq (fgh.v.in). Imports BB10_n1.v, BB10_n1_bound.v and
    BB10_n1_exact.v unchanged.  Machine: n1 = 1RB0RA_1LC1LF_1RD0LB_1RA1LE_1LI0LC_0RG1LD_1RH1LG_1LC0RG_0LJ0LI_---0LC.
    [ones c N]: the halting tape of c holds exactly N ones (the standard score is N + 1: J0 is the undefined halt).

    Standard definitions (Nat.iter n f x = f (f (... (f x)))  with n applications of f):
      fgh 0 n = n + 1,  fgh (k+1) n = (fgh k)^n (n)          f_k of the fast-growing hierarchy
      f_omega n = fgh n n,  f_omega1 n = f_omega^n (n)          f_omega and f_(omega+1)
      up3 0 n = 3 * n,  up3 (k+1) n = (up3 k)^n (1)            up3 k n = 3 ^(k arrows) n  (Knuth)
      graham_g 0 = 4,  graham_g (k+1) = up3 (graham_g k) 3     graham_g 1 = 3^^^^3, ..., Graham = graham_g 64

    Results (no axioms):
      fgh_lower      : the halting tape has N ones with f_omega1 ((3 * 2^(37 arrows) 3 - 13) / 7 - 2) < N
      fgh_lower_64   : ... with f_omega1 64 < N
      graham_lt_f_omega1_64 : Graham < f_omega1 64
      beats_graham   : ... with Graham < N
      fgh_level      : f_omega1 ((3 T - 13)/7 - 2) < N < f_omega1 (6 T), T = 2^(37 arrows) 3, for the exact N  *)

From BB8 Require Import Individual102.
From BB8 Require Import BB10_n1 BB10_n1_bound BB10_n1_exact.
From Coq Require Import Lia PeanoNat List.
Import ListNotations.
Set Default Goal Selector "!".

Local Open Scope nat_scope.

(** ** Definitions *)

Fixpoint fgh (k n : nat) : nat :=
  match k with
  | O => S n
  | S k' => Nat.iter n (fgh k') n
  end.

Definition f_omega (n : nat) : nat := fgh n n.

Definition f_omega1 (n : nat) : nat := Nat.iter n f_omega n.

Fixpoint up3 (k n : nat) : nat :=
  match k with
  | O => 3 * n
  | S k' => Nat.iter n (up3 k') 1
  end.

Fixpoint graham_g (k : nat) : nat :=
  match k with
  | O => 4
  | S k' => up3 (graham_g k') 3
  end.

Definition Graham : nat := graham_g 64.

(** sanity checks of the definitions on small values *)
Example fgh_1_5 : fgh 1 5 = 10. Proof. reflexivity. Qed.
Example fgh_2_3 : fgh 2 3 = 24. Proof. reflexivity. Qed.
Example up3_1_4 : up3 1 4 = 81. Proof. reflexivity. Qed.
Example up3_2_2 : up3 2 2 = 27. Proof. reflexivity. Qed.

Opaque U arrow F.

(** ** Basic facts *)

Lemma iter_nat : forall n (g : nat -> nat) x, Nat.iter n g x = iter n g x.
Proof. induction n; intros; simpl; [reflexivity | rewrite IHn; reflexivity]. Qed.

Lemma fgh_0 : forall n, fgh 0 n = S n.
Proof. reflexivity. Qed.

Lemma fgh_S : forall k n, fgh (S k) n = iter n (fgh k) n.
Proof. intros. simpl. apply iter_nat. Qed.

Lemma f_omega1_iter : forall n, f_omega1 n = iter n f_omega n.
Proof. intros. unfold f_omega1. apply iter_nat. Qed.

Lemma up3_0 : forall n, up3 0 n = 3 * n.
Proof. reflexivity. Qed.

Lemma up3_S : forall k n, up3 (S k) n = iter n (up3 k) 1.
Proof. intros. simpl. apply iter_nat. Qed.

Opaque fgh up3.

Lemma iter_mono_x : forall g, (forall a b, a <= b -> g a <= g b) -> forall n x y, x <= y -> iter n g x <= iter n g y.
Proof. intros g Hg. induction n; intros; simpl; [assumption | apply Hg, IHn; assumption]. Qed.

Lemma arrow_iter_mono : forall K n x y, x <= y -> iter n (arrow K 2) x <= iter n (arrow K 2) y.
Proof. intros. apply iter_mono_x; [intros; apply arrow_mono; assumption | assumption]. Qed.

Lemma fgh_ge : forall k n, n <= fgh k n.
Proof.
  induction k; intros n; [rewrite fgh_0; lia |].
  rewrite fgh_S. apply iter_ge. exact IHk.
Qed.

Lemma f_omega_ge : forall x, x <= f_omega x.
Proof. intros. apply fgh_ge. Qed.

Lemma iter_fo_ge : forall j x, x <= iter j f_omega x.
Proof. intros. apply iter_ge. exact f_omega_ge. Qed.

(** ** Upper bound of f_k by arrows, hence f_omega x <= F (F x) *)

Lemma arrow2_3x : forall x, 3 <= x -> 3 * x <= arrow 2 2 x.
Proof.
  intros x Hx. induction Hx.
  - rewrite (arrow_SS 1 2 2), (arrow_two 2), arrow_1_pow. simpl. lia.
  - pose proof (arrow_step2 1 m). lia.
Qed.

Lemma arrow_3x : forall k x, 3 <= x -> 3 * x <= arrow (S (S k)) 2 x.
Proof.
  intros. pose proof (arrow2_3x x H). pose proof (arrow_lvl_le 2 (S (S k)) x ltac:(lia) ltac:(lia)). lia.
Qed.

Lemma fgh_le : forall k n, 3 <= n -> fgh k n <= arrow (S (S k)) 2 (3 * n).
Proof.
  induction k as [| k IH]; intros n Hn.
  - rewrite fgh_0. pose proof (arrow_gt 2 (3 * n) ltac:(lia)). lia.
  - rewrite fgh_S.
    assert (Hj : forall j, iter j (fgh k) n <= iter (2 * j) (arrow (S (S k)) 2) n).
    { induction j as [| j IHj]; [simpl; lia |].
      replace (2 * S j) with (S (S (2 * j))) by lia. cbn [iter].
      pose proof (fgh_ge k n). pose proof (iter_ge (fgh k) (fgh_ge k) j n) as Hge.
      set (y := iter j (fgh k) n) in *. set (z := iter (2 * j) (arrow (S (S k)) 2) n) in *.
      pose proof (IH y ltac:(lia)) as H1.
      pose proof (arrow_3x k y ltac:(lia)) as H2.
      pose proof (arrow_mono (S (S k)) _ _ H2) as H3.
      pose proof (arrow_mono (S (S k)) _ _ IHj) as H4. pose proof (arrow_mono (S (S k)) _ _ H4) as H5.
      lia. }
    specialize (Hj n).
    pose proof (arrow_S_ge (S (S k)) n) as H1.
    pose proof (arrow_iter_mono (S (S k)) (2 * n) n (arrow (S (S (S k))) 2 n) ltac:(lia)) as H2.
    rewrite <- arrow_add in H2. replace (2 * n + n) with (3 * n) in H2 by lia. lia.
Qed.

Lemma f_omega_le : forall x, 3 <= x -> f_omega x <= F (F x).
Proof.
  intros x Hx. unfold f_omega.
  pose proof (fgh_le x x Hx) as H1.
  pose proof (F_lin (S (S x)) ltac:(lia)) as H2.
  pose proof (arrow_mono (S (S x)) (3 * x) (F (S (S x))) ltac:(lia)) as H3.
  rewrite <- F_S in H3.
  pose proof (F_ge x) as H4. pose proof (F_mono (S (S (S x))) (F x) ltac:(lia)) as H5.
  lia.
Qed.

Lemma fo_iter_le : forall j m, 3 <= m -> iter j f_omega m <= iter (2 * j) F m.
Proof.
  induction j as [| j IH]; intros m Hm; [simpl; lia |].
  replace (2 * S j) with (S (S (2 * j))) by lia. cbn [iter].
  pose proof (iter_fo_ge j m). pose proof (IH m Hm).
  pose proof (f_omega_le (iter j f_omega m) ltac:(lia)).
  pose proof (F_mono _ _ (F_mono _ _ H0)). lia.
Qed.

(** ** Lower bounds for n1 *)

Lemma JJ_ge : 142 <= JJ.
Proof.
  destruct JJ_eq as [HJ _]. pose proof (F_lin 36 ltac:(lia)) as H.
  rewrite <- arrow_S3, <- T_def in H. revert HJ H. generalize T JJ. intros. lia.
Qed.

Lemma T_le : T <= F (F 34).
Proof. rewrite T_def, arrow_S3. apply F_mono. pose proof (F_lin 34 ltac:(lia)). lia. Qed.

Lemma JJ_le_T : JJ <= T.
Proof. unfold JJ. apply Nat.div_le_upper_bound; lia. Qed.

Theorem fgh_lower : exists c N, c0 -->* c /\ halted tm c /\ ones c N /\
  f_omega1 ((3 * arrow 37 2 3 - 13) / 7 - 2) < N.
Proof.
  destruct score_ge as [c [N [H1 [H2 [H3 H4]]]]].
  exists c, N. split; [exact H1 | split; [exact H2 | split; [exact H3 |]]].
  rewrite <- JJ_closed, f_omega1_iter. pose proof JJ_ge as HJ. pose proof JJ_le_T. pose proof T_le.
  pose proof (fo_iter_le (JJ - 2) (JJ - 2) ltac:(lia)) as A1.
  replace (2 * JJ + 1) with (2 * (JJ - 2) + 5) in H4 by lia. rewrite iter_add in H4.
  pose proof (iter_big 5 ltac:(lia)) as A2. pose proof (F_ge (F (F 34))) as A3.
  pose proof (iterF_mono (2 * (JJ - 2)) (JJ - 2) (iter 5 F 34) ltac:(lia)) as A4.
  lia.
Qed.

Theorem fgh_lower_64 : exists c N, c0 -->* c /\ halted tm c /\ ones c N /\ f_omega1 64 < N.
Proof.
  destruct score_ge as [c [N [H1 [H2 [H3 H4]]]]].
  exists c, N. split; [exact H1 | split; [exact H2 | split; [exact H3 |]]].
  rewrite f_omega1_iter. pose proof JJ_ge as HJ.
  pose proof (fo_iter_le 64 64 ltac:(lia)) as A1.
  replace (2 * JJ + 1) with (2 * 64 + (2 * JJ + 1 - 128)) in H4 by lia. rewrite iter_add in H4.
  replace (2 * JJ + 1 - 128) with (S (2 * JJ - 128)) in H4 by lia.
  pose proof (iterF_ge (2 * JJ - 128) 34) as A2. pose proof (F_mono _ _ A2) as A3.
  pose proof (F_lin 34 ltac:(lia)) as A4. change (iter (S (2 * JJ - 128)) F 34) with (F (iter (2 * JJ - 128) F 34)) in H4.
  pose proof (iterF_mono (2 * 64) 64 (F (iter (2 * JJ - 128) F 34)) ltac:(lia)) as A5.
  lia.
Qed.

(** ** Graham's number *)

Lemma up3_le : forall k n, up3 k n <= arrow k 2 (2 * n).
Proof.
  induction k as [| k IH]; intros n.
  - rewrite up3_0, (arrow_0 2 (2 * n)). lia.
  - rewrite up3_S, arrow_S_iter.
    induction n as [| n IHn]; [simpl; lia |].
    replace (2 * S n) with (S (S (2 * n))) by lia. cbn [iter].
    pose proof (IH (iter n (up3 k) 1)) as H1.
    pose proof (arrow_double k (iter n (up3 k) 1)) as H2.
    pose proof (arrow_mono k _ _ H2) as H3.
    pose proof (arrow_mono k _ _ IHn) as H4. pose proof (arrow_mono k _ _ H4) as H5.
    lia.
Qed.

Lemma fgh1 : forall n, fgh 1 n = 2 * n.
Proof.
  intros. rewrite fgh_S. assert (forall j x, iter j (fgh 0) x = j + x).
  { induction j; intros; simpl; [lia | rewrite IHj, fgh_0; lia]. }
  rewrite H. lia.
Qed.

Lemma fgh_arrow_ge : forall k n, 1 <= n -> arrow k 2 n <= fgh (S k) n.
Proof.
  induction k as [| k IH]; intros n Hn.
  - rewrite fgh1, (arrow_0 2 n). lia.
  - rewrite fgh_S, arrow_S_iter.
    assert (Hj : forall j, iter j (arrow k 2) n <= iter j (fgh (S k)) n).
    { induction j as [| j IHj]; [simpl; lia |]. cbn [iter].
      pose proof (iter_ge (fgh (S k)) (fgh_ge (S k)) j n).
      pose proof (arrow_mono k _ _ IHj). pose proof (IH (iter j (fgh (S k)) n) ltac:(lia)). lia. }
    specialize (Hj n). pose proof (arrow_iter_mono k n 1 n Hn). lia.
Qed.

Lemma arrow_strict : forall k y z, y < z -> arrow k 2 y < arrow k 2 z.
Proof.
  intros k y z Hyz. destruct k as [| k].
  - rewrite (arrow_0 2 y), (arrow_0 2 z). lia.
  - pose proof (arrow_step2 k y) as H1. pose proof (arrow_S_ge k y) as H2.
    pose proof (arrow_mono (S k) (S y) z Hyz). lia.
Qed.

Lemma graham_lt : forall j, graham_g j < iter j f_omega 64.
Proof.
  induction j as [| j IH]; [simpl; lia |].
  change (graham_g (S j)) with (up3 (graham_g j) 3). cbn [iter].
  set (x := iter j f_omega 64) in *.
  pose proof (iter_fo_ge j 64) as Hx. fold x in Hx.
  pose proof (up3_le (graham_g j) 3) as H1. change (2 * 3) with 6 in H1.
  pose proof (arrow_lvl_le (graham_g j) (x - 1) 6 ltac:(lia) ltac:(lia)) as H2.
  pose proof (arrow_strict (x - 1) 6 x ltac:(lia)) as H3.
  pose proof (fgh_arrow_ge (x - 1) x ltac:(lia)) as H4. replace (S (x - 1)) with x in H4 by lia.
  unfold f_omega. lia.
Qed.

Theorem graham_lt_f_omega1_64 : Graham < f_omega1 64.
Proof. unfold Graham. rewrite f_omega1_iter. apply graham_lt. Qed.

Theorem beats_graham : exists c N, c0 -->* c /\ halted tm c /\ ones c N /\ Graham < N.
Proof.
  destruct fgh_lower_64 as [c [N [H1 [H2 [H3 H4]]]]].
  exists c, N. split; [exact H1 | split; [exact H2 | split; [exact H3 |]]].
  pose proof graham_lt_f_omega1_64. lia.
Qed.

(** ** Upper bound: n1 stays below f_(omega+1)(6 T) *)

Lemma fgh_mono_n : forall k x y, x <= y -> fgh k x <= fgh k y.
Proof.
  induction k as [| k IH]; intros x y Hxy; [rewrite (fgh_0 x), (fgh_0 y); lia |].
  rewrite !fgh_S.
  pose proof (iter_mono_x (fgh k) (IH) x x y Hxy).
  pose proof (iter_mono_n (fgh k) (fgh_ge k) x y y Hxy). lia.
Qed.

Lemma fgh_lvl1 : forall k n, 1 <= n -> fgh k n <= fgh (S k) n.
Proof.
  intros k n Hn. rewrite fgh_S.
  pose proof (iter_mono_n (fgh k) (fgh_ge k) 1 n n Hn). cbn [iter] in H. lia.
Qed.

Lemma fgh_lvl : forall k K n, k <= K -> 1 <= n -> fgh k n <= fgh K n.
Proof. intros k K n HkK Hn. induction HkK; [lia |]. pose proof (fgh_lvl1 m n Hn). lia. Qed.

Lemma fgh2 : forall y, fgh 2 y = 2 ^ y * y.
Proof.
  intros. rewrite fgh_S.
  assert (forall j x, iter j (fgh 1) x = 2 ^ j * x).
  { induction j; intros; cbn [iter]; [simpl; lia | rewrite IHj, fgh1, Nat.pow_succ_r'; lia]. }
  apply H.
Qed.

Lemma fo_mono : forall x y, x <= y -> f_omega x <= f_omega y.
Proof.
  intros x y Hxy. unfold f_omega. destruct y as [| y'].
  - assert (x = 0) by lia. subst. lia.
  - pose proof (fgh_mono_n x x (S y') Hxy). pose proof (fgh_lvl x (S y') (S y') Hxy ltac:(lia)). lia.
Qed.

Lemma fo_4 : forall y, 2 <= y -> 4 * y <= f_omega y.
Proof.
  intros y Hy. unfold f_omega. pose proof (fgh_lvl 2 y y Hy ltac:(lia)). rewrite fgh2 in H.
  assert (4 <= 2 ^ y) by (change 4 with (2 ^ 2); apply Nat.pow_le_mono_r; lia).
  nia.
Qed.

Lemma fo_dbl : forall y, 1 <= y -> 2 * f_omega y <= f_omega (S y).
Proof.
  intros y Hy. unfold f_omega. rewrite fgh_S.
  pose proof (iter_mono_n (fgh y) (fgh_ge y) 2 (S y) (S y) ltac:(lia)) as H1.
  change (iter 2 (fgh y) (S y)) with (fgh y (fgh y (S y))) in H1.
  pose proof (fgh_mono_n y y (S y) ltac:(lia)) as H2.
  pose proof (fgh_ge y (S y)) as H3.
  pose proof (fgh_lvl 1 y (fgh y (S y)) Hy ltac:(lia)) as H4. rewrite fgh1 in H4.
  lia.
Qed.

Lemma fo_ge1 : forall y, 1 <= y -> y <= f_omega y.
Proof. intros. apply f_omega_ge. Qed.

Lemma fo_shift : forall c y, 1 <= y -> f_omega y + c <= f_omega (y + c).
Proof.
  induction c as [| c IH]; intros y Hy; [rewrite !Nat.add_0_r; lia |].
  replace (y + S c) with (S (y + c)) by lia.
  pose proof (IH y Hy). pose proof (fo_dbl (y + c) ltac:(lia)). pose proof (f_omega_ge (y + c)). lia.
Qed.

Lemma arrow_fo : forall k z, 1 <= z -> arrow k 2 z <= f_omega (k + z + 1).
Proof.
  intros k z Hz. unfold f_omega.
  pose proof (fgh_arrow_ge k z Hz).
  pose proof (fgh_lvl (S k) (k + z + 1) z ltac:(lia) Hz).
  pose proof (fgh_mono_n (k + z + 1) z (k + z + 1) ltac:(lia)). lia.
Qed.

Lemma iterfo_mono : forall a b y z, a <= b -> y <= z -> iter a f_omega y <= iter b f_omega z.
Proof.
  intros a b y z Hab Hyz.
  pose proof (iter_mono_x f_omega fo_mono a y z Hyz).
  pose proof (iter_mono_n f_omega f_omega_ge a b z Hab). lia.
Qed.

Lemma iterfo_shift : forall a y c, 1 <= y -> iter a f_omega y + c <= iter a f_omega (y + c).
Proof.
  induction a as [| a IH]; intros y c Hy; [cbn [iter]; lia |].
  cbn [iter]. pose proof (iter_fo_ge a y).
  pose proof (fo_shift c (iter a f_omega y) ltac:(lia)).
  pose proof (fo_mono _ _ (IH y c Hy)). lia.
Qed.

(** one period at most multiplies the size x = 2 (n + g) + 6 into f_omega^8 (x) *)
Lemma step_bound : forall n g, 3 <= n -> 3 <= g ->
  2 * (fst (step (n, g)) + snd (step (n, g))) + 6 <= iter 8 f_omega (2 * (n + g) + 6).
Proof.
  intros n g Hn Hg. unfold step. cbn [fst snd].
  remember (2 * (n + g) + 6) as x eqn:Ex.
  remember (n + 2 * g - 6) as n2 eqn:En2.
  remember (arrow n 2 5) as a1 eqn:Ea1.
  remember (arrow n2 2 5) as a2 eqn:Ea2.
  remember (arrow (S n2) 2 (a1 - 1)) as A eqn:EA.
  remember (arrow (S (n2 + 2 * A - 4)) 2 (a2 - 1)) as G eqn:EG.
  pose proof (arrow5 n) as A5. pose proof (arrow5 n2) as A5'. rewrite <- Ea1 in A5. rewrite <- Ea2 in A5'.
  pose proof (arrow_fo n 5 ltac:(lia)) as Ha1. rewrite <- Ea1 in Ha1.
  pose proof (fo_mono (n + 5 + 1) x ltac:(lia)) as Ha1'.
  pose proof (fo_4 x ltac:(lia)) as Fx. pose proof (fo_dbl x ltac:(lia)) as D1. pose proof (fo_dbl (S x) ltac:(lia)) as D2.
  pose proof (arrow_fo (S n2) (a1 - 1) ltac:(lia)) as HA. rewrite <- EA in HA.
  pose proof (fo_mono (S n2 + (a1 - 1) + 1) (f_omega (S (S x))) ltac:(lia)) as HA'.
  remember (f_omega (f_omega (S (S x)))) as Y eqn:EY.
  pose proof (fo_4 (S (S x)) ltac:(lia)) as Fx2.
  pose proof (fo_ge1 (f_omega (S (S x))) ltac:(lia)) as GY. rewrite <- EY in GY.
  pose proof (arrow_fo n2 5 ltac:(lia)) as Ha2. rewrite <- Ea2 in Ha2.
  pose proof (fo_mono (n2 + 5 + 1) (f_omega (S (S x))) ltac:(lia)) as Ha2'.
  pose proof (arrow_fo (S (n2 + 2 * A - 4)) (a2 - 1) ltac:(lia)) as HG. rewrite <- EG in HG.
  pose proof (fo_4 Y ltac:(lia)) as FY. pose proof (fo_dbl Y ltac:(lia)) as DY.
  pose proof (fo_mono (S (n2 + 2 * A - 4) + (a2 - 1) + 1) (f_omega (S Y)) ltac:(lia)) as HG'.
  remember (f_omega (f_omega (S Y))) as Z eqn:EZ.
  pose proof (fo_ge1 (f_omega (S Y)) ltac:(lia)) as GZ. rewrite <- EZ in GZ. pose proof (fo_4 (S Y) ltac:(lia)) as FSY.
  pose proof (fo_4 Z ltac:(lia)) as FZ. pose proof (fo_dbl Z ltac:(lia)) as DZ. pose proof (fo_dbl (S Z) ltac:(lia)) as DZ2.
  assert (Step1 : 2 * (n2 + 2 * A - 4 + G) + 6 <= f_omega (S (S Z))) by lia.
  assert (C1 : S Y <= f_omega Y) by lia.
  assert (C2 : Z <= iter 3 f_omega Y).
  { rewrite EZ. cbn [iter]. apply fo_mono, fo_mono. exact C1. }
  assert (C3 : S (S Z) <= f_omega Z) by lia.
  assert (C4 : f_omega (S (S Z)) <= iter 5 f_omega Y).
  { pose proof (fo_mono _ _ C3). pose proof (fo_mono _ _ (fo_mono _ _ C2)).
    change (iter 5 f_omega Y) with (f_omega (f_omega (iter 3 f_omega Y))). lia. }
  assert (C5 : iter 5 f_omega Y = iter 7 f_omega (S (S x))) by (rewrite EY; reflexivity).
  assert (C6 : S (S x) <= f_omega x) by lia.
  pose proof (iterfo_mono 7 7 (S (S x)) (f_omega x) (le_n _) C6) as C7.
  change (iter 8 f_omega x) with (iter 7 f_omega (f_omega x)).
  lia.
Qed.

Lemma stepn_bound : forall J n g, 3 <= n -> F n <= g ->
  2 * (fst (stepn J (n, g)) + snd (stepn J (n, g))) + 6 <= iter (8 * J) f_omega (2 * (n + g) + 6).
Proof.
  induction J as [| J IH]; intros n g Hn Hg; [change (8 * 0) with 0; cbn [stepn fst snd iter]; lia |].
  pose proof (F_ge n).
  destruct (step_props n g Hn Hg) as [S1 [S2 _]].
  pose proof (step_bound n g Hn ltac:(lia)) as SB.
  destruct (step (n, g)) as [n' g'] eqn:Es. cbn [fst snd] in S1, S2, SB.
  change (stepn (S J) (n, g)) with (stepn J (step (n, g))). rewrite Es.
  pose proof (IH n' g' S1 S2) as H1.
  pose proof (iterfo_mono (8 * J) (8 * J) _ _ (le_n _) SB) as H2.
  replace (8 * S J) with (8 * J + 8) by lia. rewrite iter_add. lia.
Qed.

Lemma x0_bound : 2 * (34 + g0) + 6 <= iter 2 f_omega 43.
Proof.
  unfold g0. pose proof (arrow5 34) as A.
  pose proof (arrow_fo 34 5 ltac:(lia)) as H1. change (34 + 5 + 1) with 40 in H1.
  pose proof (arrow_fo 35 (arrow 34 2 5 - 1) ltac:(lia)) as H2.
  pose proof (fo_4 40 ltac:(lia)) as F40. pose proof (fo_dbl 40 ltac:(lia)) as D40. pose proof (fo_dbl 41 ltac:(lia)) as D41.
  pose proof (fo_dbl 42 ltac:(lia)) as D42.
  pose proof (fo_mono (35 + (arrow 34 2 5 - 1) + 1) (f_omega 42) ltac:(lia)) as H3.
  pose proof (fo_4 (f_omega 42) ltac:(lia)) as F4.
  pose proof (fo_dbl (f_omega 42) ltac:(lia)) as D4. pose proof (fo_dbl (S (f_omega 42)) ltac:(lia)) as D5.
  pose proof (fo_mono (S (S (f_omega 42))) (f_omega 43) ltac:(lia)) as H4.
  change (iter 2 f_omega 43) with (f_omega (f_omega 43)).
  revert A H1 H2 F40 D40 D41 D42 H3 F4 D4 D5 H4.
  generalize (arrow 34 2 5) (arrow 35 2 (arrow 34 2 5 - 1)) (f_omega 40) (f_omega 41) (f_omega 42) (f_omega 43)
    (f_omega (f_omega 42)) (f_omega (S (f_omega 42))) (f_omega (S (S (f_omega 42)))) (f_omega (f_omega 43)).
  intros. lia.
Qed.

Lemma final_bound : forall n g J x, 3 <= n -> F n <= g -> 142 <= J -> x = 2 * (n + g) + 6 ->
  x <= iter (8 * J) f_omega (iter 2 f_omega 43) ->
  2 * (n + 2 * g - 6) + 3 * arrow (S (n + 2 * g - 6)) 2 (arrow n 2 5) + 12 * J + 5 < iter (12 * J + 48) f_omega (12 * J + 48).
Proof.
  intros n g J x Hn Hg HJ Ex HX.
  pose proof (F_ge n) as Fn.
  remember (x + 12 * J + 5) as u eqn:Eu.
  remember (arrow n 2 5) as a eqn:Ea.
  remember (arrow (S (n + 2 * g - 6)) 2 a) as V eqn:EV.
  pose proof (arrow5 n) as A5. rewrite <- Ea in A5.
  pose proof (arrow_fo n 5 ltac:(lia)) as Ha. rewrite <- Ea in Ha.
  pose proof (fo_mono (n + 5 + 1) x ltac:(lia)) as Ha'.
  pose proof (arrow_fo (S (n + 2 * g - 6)) a ltac:(lia)) as HV. rewrite <- EV in HV.
  pose proof (fo_4 x ltac:(lia)) as Fx. pose proof (fo_dbl x ltac:(lia)) as D1. pose proof (fo_dbl (S x) ltac:(lia)) as D2.
  pose proof (fo_mono (S (S x)) (S (S u)) ltac:(lia)) as M1.
  pose proof (fo_mono (S (n + 2 * g - 6) + a + 1) (f_omega (S (S u))) ltac:(lia)) as HV'.
  remember (f_omega (f_omega (S (S u)))) as Q eqn:EQ.
  pose proof (fo_ge1 (f_omega (S (S u))) ltac:(lia)) as GQ. rewrite <- EQ in GQ. pose proof (fo_4 (S (S u)) ltac:(lia)) as F2u.
  pose proof (fo_4 Q ltac:(lia)) as FQ. pose proof (fo_dbl Q ltac:(lia)) as DQ.
  assert (N1 : 2 * (n + 2 * g - 6) + 3 * V + 12 * J + 5 < f_omega (S Q)) by lia.
  assert (N2 : f_omega (S Q) <= iter 5 f_omega u).
  { pose proof (fo_mono (S Q) (f_omega Q) ltac:(lia)) as K1.
    pose proof (fo_4 u ltac:(lia)) as K2. pose proof (iterfo_mono 4 4 (S (S u)) (f_omega u) (le_n _) ltac:(lia)) as K3.
    change (iter 5 f_omega u) with (iter 4 f_omega (f_omega u)).
    assert (K4 : iter 4 f_omega (S (S u)) = f_omega (f_omega Q)) by (rewrite EQ; reflexivity).
    lia. }
  assert (N3 : u <= iter (8 * J + 2) f_omega (12 * J + 48)).
  { pose proof (iter_fo_ge 2 43) as K0.
    pose proof (iterfo_shift (8 * J) (iter 2 f_omega 43) (12 * J + 5) ltac:(lia)) as S1.
    pose proof (iterfo_shift 2 43 (12 * J + 5) ltac:(lia)) as S2.
    pose proof (iterfo_mono (8 * J) (8 * J) _ _ (le_n _) S2) as S3.
    rewrite iter_add. replace (43 + (12 * J + 5)) with (12 * J + 48) in S3 by lia. lia. }
  pose proof (iterfo_mono 5 5 _ _ (le_n _) N3) as N4. rewrite <- iter_add in N4.
  pose proof (iterfo_mono (5 + (8 * J + 2)) (12 * J + 48) (12 * J + 48) (12 * J + 48) ltac:(lia) (le_n _)) as N5.
  lia.
Qed.

Lemma score_value_lt : score_value < f_omega1 (12 * JJ + 48).
Proof.
  destruct fin_props as [H1 [H2 _]].
  pose proof (stepn_bound JJ 34 g0 ltac:(lia) g0_ge) as SB. fold fin in SB.
  pose proof (iterfo_mono (8 * JJ) (8 * JJ) _ _ (le_n _) x0_bound) as X0.
  pose proof JJ_ge as HJ.
  rewrite f_omega1_iter. unfold score_value, Wf.
  apply (final_bound (fst fin) (snd fin) JJ (2 * (fst fin + snd fin) + 6) H1 H2 HJ eq_refl). lia.
Qed.

Lemma lower_from : forall N, iter (2 * JJ + 1) F 34 < N -> f_omega1 (JJ - 2) < N.
Proof.
  intros N H4. rewrite f_omega1_iter. pose proof JJ_ge as HJ. pose proof JJ_le_T. pose proof T_le.
  pose proof (fo_iter_le (JJ - 2) (JJ - 2) ltac:(lia)) as A1.
  replace (2 * JJ + 1) with (2 * (JJ - 2) + 5) in H4 by lia. rewrite iter_add in H4.
  pose proof (iter_big 5 ltac:(lia)) as A2. pose proof (F_ge (F (F 34))) as A3.
  pose proof (iterF_mono (2 * (JJ - 2)) (JJ - 2) (iter 5 F 34) ltac:(lia)) as A4.
  lia.
Qed.

Lemma f_omega1_mono : forall a b, a <= b -> f_omega1 a <= f_omega1 b.
Proof. intros. rewrite !f_omega1_iter. apply iterfo_mono; assumption. Qed.

(** n1 sits at level omega+1: f_(omega+1)(J - 2) < sigma - 1 < f_(omega+1)(6 T), J = (3T - 13)/7 *)
Theorem fgh_level : exists c N, c0 -->* c /\ halted tm c /\ ones c N /\
  f_omega1 ((3 * arrow 37 2 3 - 13) / 7 - 2) < N /\ N < f_omega1 (6 * arrow 37 2 3).
Proof.
  destruct score_closed as [c [H1 [H2 H3]]].
  exists c, score_value. split; [exact H1 | split; [exact H2 | split; [exact H3 |]]].
  rewrite <- JJ_closed, <- T_def. split.
  - apply lower_from. exact score_value_gt.
  - pose proof score_value_lt. destruct JJ_eq as [HJ _]. pose proof JJ_ge.
    pose proof (f_omega1_mono (12 * JJ + 48) (6 * T) ltac:(lia)). lia.
Qed.


Print Assumptions fgh_lower.
Print Assumptions fgh_lower_64.
Print Assumptions graham_lt_f_omega1_64.
Print Assumptions beats_graham.
Print Assumptions fgh_level.
