(** * Closed-form score of the BB(10) candidate n1 = 1RB0RA_1LC1LF_1RD0LB_1RA1LE_1LI0LC_0RG1LD_1RH1LG_1LC0RG_0LJ0LI_---0LC *)

(** Generated by bb8_list/investigations/bb10_n1_coq (exact.v.in). Imports BB10_n1.v and BB10_n1_bound.v unchanged.

    The run passes JJ = (3 T - 13) / 7 periods, T = 2 ^(37 arrows) 3. A period start Per k m n a (n = zero-block
    length, a = accumulator) is tracked by the pair (n, g) with a = 3 g - 8. One period maps (n, g) to [step (n, g)]:
      n2 = n + 2 g - 6                                            (the P2 growth: the parked accumulator is unpacked)
      n4 = n2 + 2 * 2 ^(n2+1 arrows) (2 ^(n arrows) 5 - 1) - 4    (the P4 growth)
      g' = 2 ^(n4+1 arrows) (2 ^(n2 arrows) 5 - 1)                 (the next accumulator)
    The first period starts from (34, 2 ^(35 arrows) (2 ^(34 arrows) 5 - 1)). With (n, g) after JJ periods and
    W = n + 2 g - 6 (the final zero block), the halting tape has exactly
      2 W + 3 * 2 ^(W+1 arrows) (2 ^(n arrows) 5) + 12 JJ + 5
    ones (Theorem score_closed); the standard score is one more.  score_value_gt: the value exceeds F^(2 JJ + 1)(34),
    the lower bound of BB10_n1_bound.v (F n = 2 ^(n arrows) 4). *)

From BB8 Require Import Individual102.
From BB8 Require Import BB10_n1 BB10_n1_bound.
From Coq Require Import Lia PeanoNat List.
Import ListNotations.
Set Default Goal Selector "!".

Local Open Scope nat_scope.

Opaque U arrow F.

(** ** The closed form of a clearing from 4: (U j)^d (4) = 3 * 2 ^(j+1 arrows) (d + 2) - 8 *)

Lemma iterU : forall j d, iter d (U j) 4 + 8 = 3 * arrow (S j) 2 (d + 2).
Proof.
  intros j. induction d as [| d IH].
  - change (iter 0 (U j) 4) with 4. rewrite arrow_two. reflexivity.
  - change (iter (S d) (U j) 4) with (U j (iter d (U j) 4)).
    replace (S d + 2) with (S (d + 2)) by lia. rewrite arrow_SS.
    pose proof (arrow_ge4 (S j) (d + 2) ltac:(lia)) as H4.
    revert IH H4. generalize (iter d (U j) 4) (arrow (S j) 2 (d + 2)). intros A X IH H4.
    replace A with (3 * (X - 3) + 1) by lia.
    rewrite U_closed. replace (X - 3 + 3) with X by lia. reflexivity.
Qed.

Lemma iterU_eq : forall j d, iter d (U j) 4 = 1 + 3 * (arrow (S j) 2 (d + 2) - 3).
Proof.
  intros. pose proof (iterU j d). pose proof (arrow_ge4 (S j) (d + 2) ltac:(lia)).
  revert H H0. generalize (iter d (U j) 4) (arrow (S j) 2 (d + 2)). intros. lia.
Qed.

Lemma arrow5 : forall n, 6 <= arrow n 2 5.
Proof. intros. pose proof (arrow_gt n 5 ltac:(lia)). lia. Qed.

(** ** One period with every value explicit (the script of PERIOD, without the existentials) *)

Lemma PERIOD_U : forall k m w p x y x',
  iter 3 (U (S w)) 4 = 1 + 3 * x -> iter x (U (2 + w + 2 * p)) 4 = 1 + 3 * y ->
  iter 3 (U (1 + w + 2 * p)) 4 = 1 + 3 * x' ->
  Per k (14 + m) (S (S w)) (1 + 3 * p) -->*
  Per (4 + k) m (2 + (w + 2 * p) + 2 * S y) (iter x' (U (2 + (w + 2 * p) + 2 * S y)) 4).
Proof.
  intros k m w p x y x' Hx Hy Hx'.
  unfold Per.
  replace (14 + m) with (6 + (8 + m)) by lia.
  follow (P1_B k (8 + m) (S (S w)) (1 + 3 * p)).
  follow (DEP9 (const 0%sym) (S w) (1 + 3 * p) (1 :: 0 :: 0 :: 0 :: repeat 1 (8 + m) ++ 5 :: repeat 2 (2 + k))).
  rewrite Hx. replace (8 + m) with (6 + (2 + m)) by lia.
  follow (P2_B (2 + k) (2 + m) p (3 * x) w). rewrite merge3.
  follow (CLR (2 + w + 2 * p) x 2 [2] (FarP (2 + k) (2 + m)) 4 (or_intror r1_4)).
  follow (P3_B (2 + k) (2 + m) (2 + w + 2 * p) (iter x (U (2 + w + 2 * p)) 4)).
  rewrite Hy. replace (5 + (1 + 3 * y)) with (3 + (3 + 3 * y)) by lia. replace (2 + (2 + k)) with (4 + k) by lia.
  follow (DEP9 (const 0%sym) (1 + w + 2 * p) (3 + 3 * y) (0 :: 0 :: repeat 1 (2 + m) ++ 5 :: repeat 2 (4 + k))).
  rewrite Hx'. replace (3 + 3 * y) with (3 * S y) by lia.
  replace (1 + w + 2 * p) with (1 + (w + 2 * p)) by lia.
  follow (P4_B (4 + k) m (S y) (3 * x') (w + 2 * p)). rewrite merge3.
  apply (CLR (2 + (w + 2 * p) + 2 * S y) x' 2 _ (const 0%sym) 4 (or_intror r1_4)).
Qed.

(** ** The period map on (n, g), a = 3 g - 8 *)

Definition step (s : nat * nat) : nat * nat :=
  let n := fst s in
  let g := snd s in
  let n2 := n + 2 * g - 6 in
  let n4 := n2 + 2 * arrow (S n2) 2 (arrow n 2 5 - 1) - 4 in
  (n4, arrow (S n4) 2 (arrow n2 2 5 - 1)).

Fixpoint stepn (j : nat) (s : nat * nat) : nat * nat :=
  match j with
  | O => s
  | S j' => stepn j' (step s)
  end.

Lemma PERIOD_G : forall k m n g, 3 <= n -> 4 <= g ->
  Per k (14 + m) n (3 * g - 8) -->* Per (4 + k) m (fst (step (n, g))) (3 * snd (step (n, g)) - 8).
Proof.
  intros k m n g Hn Hg.
  destruct n as [| n1]; [lia |]. destruct n1 as [| w]; [lia |].
  set (p := g - 3).
  set (x := arrow (S (S w)) 2 5 - 3).
  set (n2 := 2 + w + 2 * p).
  set (y := arrow (S n2) 2 (x + 2) - 3).
  set (x' := arrow n2 2 5 - 3).
  assert (Hx : iter 3 (U (S w)) 4 = 1 + 3 * x) by (unfold x; apply iterU_eq).
  assert (Hy : iter x (U (2 + w + 2 * p)) 4 = 1 + 3 * y) by (unfold y, n2; apply iterU_eq).
  assert (Hx' : iter 3 (U (1 + w + 2 * p)) 4 = 1 + 3 * x').
  { unfold x'. rewrite iterU_eq. unfold n2. replace (S (1 + w + 2 * p)) with (2 + w + 2 * p) by lia. reflexivity. }
  pose proof (PERIOD_U k m w p x y x' Hx Hy Hx') as HP.
  replace (3 * g - 8) with (1 + 3 * p) by (unfold p; lia).
  assert (E1 : fst (step (S (S w), g)) = 2 + (w + 2 * p) + 2 * S y).
  { unfold step. cbn [fst snd]. unfold y, x, n2, p.
    pose proof (arrow5 (S (S w))). pose proof (arrow_ge4 (S (2 + w + 2 * (g - 3))) (arrow (S (S w)) 2 5 - 3 + 2) ltac:(lia)).
    replace (S (S w) + 2 * g - 6) with (2 + w + 2 * (g - 3)) by lia.
    replace (arrow (S (S w)) 2 5 - 1) with (arrow (S (S w)) 2 5 - 3 + 2) by lia.
    revert H0. generalize (arrow (S (2 + w + 2 * (g - 3))) 2 (arrow (S (S w)) 2 5 - 3 + 2)). intros. lia. }
  assert (E2 : 3 * snd (step (S (S w), g)) - 8 = iter x' (U (2 + (w + 2 * p) + 2 * S y)) 4).
  { rewrite iterU_eq. rewrite <- E1. unfold step. cbn [fst snd].
    replace (S (S w) + 2 * g - 6) with n2 by (unfold n2, p; lia).
    unfold x'. pose proof (arrow5 n2).
    replace (arrow n2 2 5 - 1) with (arrow n2 2 5 - 3 + 2) by lia.
    set (N4 := n2 + 2 * arrow (S n2) 2 (arrow (S (S w)) 2 5 - 1) - 4).
    pose proof (arrow_ge4 (S N4) (arrow n2 2 5 - 3 + 2) ltac:(lia)).
    revert H0. generalize (arrow (S N4) 2 (arrow n2 2 5 - 3 + 2)). intros. lia. }
  rewrite E1, E2. exact HP.
Qed.

(** ** Sizes: the invariant g >= F n is kept and n grows by F twice per period *)

Lemma step_props : forall n g, 3 <= n -> F n <= g ->
  3 <= fst (step (n, g)) /\ F (fst (step (n, g))) <= snd (step (n, g)) /\ F (F n) <= fst (step (n, g)).
Proof.
  intros n g Hn Hg. unfold step. cbn [fst snd].
  pose proof (F_ge n) as HF.
  set (n2 := n + 2 * g - 6).
  assert (Hn2 : F n <= n2) by (unfold n2; lia).
  pose proof (arrow5 n) as A5. pose proof (arrow5 n2) as A5'.
  assert (G1 : F n2 <= arrow (S n2) 2 (arrow n 2 5 - 1)).
  { rewrite <- arrow_S3. apply arrow_mono. lia. }
  pose proof (F_ge n2) as HF2.
  set (n4 := n2 + 2 * arrow (S n2) 2 (arrow n 2 5 - 1) - 4).
  assert (Hn4 : F n2 <= n4) by (unfold n4; lia).
  assert (G2 : F n4 <= arrow (S n4) 2 (arrow n2 2 5 - 1)).
  { rewrite <- arrow_S3. apply arrow_mono. lia. }
  pose proof (F_mono _ _ Hn2). pose proof (F_ge n4). lia.
Qed.

Lemma PERIODS_G : forall J k n g, 3 <= n -> F n <= g ->
  Per k (14 * J + 7) n (3 * g - 8) -->* Per (4 * J + k) 7 (fst (stepn J (n, g))) (3 * snd (stepn J (n, g)) - 8) /\
  3 <= fst (stepn J (n, g)) /\ F (fst (stepn J (n, g))) <= snd (stepn J (n, g)) /\ iter (2 * J) F n <= fst (stepn J (n, g)).
Proof.
  induction J as [| J IH]; intros k n g Hn Hg.
  - cbn [stepn fst snd]. replace (14 * 0 + 7) with 7 by reflexivity. replace (4 * 0 + k) with k by reflexivity.
    split; [apply evstep_refl | split; [lia | split; [lia | change (iter (2 * 0) F n) with n; lia]]].
  - pose proof (F_ge n).
    destruct (step_props n g Hn Hg) as [S1 [S2 S3]].
    destruct (step (n, g)) as [n' g'] eqn:Es. cbn [fst snd] in S1, S2, S3.
    destruct (IH (4 + k) n' g' S1 S2) as [H1 [H2 [H3 H4]]].
    change (stepn (S J) (n, g)) with (stepn J (step (n, g))). rewrite Es.
    split; [| split; [exact H2 | split; [exact H3 |]]].
    + replace (14 * S J + 7) with (14 + (14 * J + 7)) by lia.
      replace (4 * S J + k) with (4 * J + (4 + k)) by lia.
      eapply evstep_trans; [| exact H1].
      pose proof (PERIOD_G k (14 * J + 7) n g Hn ltac:(lia)) as HP. rewrite Es in HP. cbn [fst snd] in HP. exact HP.
    + replace (2 * S J) with (2 * J + 2) by lia. rewrite iter_add.
      change (iter 2 F n) with (F (F n)). pose proof (iterF_mono (2 * J) _ _ S3). lia.
Qed.

(** ** The endgame with explicit values *)

Lemma ENDGAME_G : forall k n g, 3 <= n -> 4 <= g ->
  Per (4 + k) 7 n (3 * g - 8) -->*
  Bf (FarE k) (repeat 1 (n + 2 * g - 6) ++ [0]) (3 * arrow (S (n + 2 * g - 6)) 2 (arrow n 2 5) - 8).
Proof.
  intros k n g Hn Hg.
  destruct n as [| n1]; [lia |]. destruct n1 as [| w]; [lia |].
  set (p := g - 3). set (x := arrow (S (S w)) 2 5 - 3).
  assert (Hx : iter 3 (U (S w)) 4 = 1 + 3 * x) by (unfold x; apply iterU_eq).
  replace (3 * g - 8) with (1 + 3 * p) by (unfold p; lia).
  replace (S (S w) + 2 * g - 6) with (2 + w + 2 * p) by (unfold p; lia).
  assert (Ef : 3 * arrow (S (2 + w + 2 * p)) 2 (arrow (S (S w)) 2 5) - 8 = iter (S x) (U (2 + w + 2 * p)) 4).
  { rewrite iterU_eq. unfold x. pose proof (arrow5 (S (S w))).
    replace (S (arrow (S (S w)) 2 5 - 3) + 2) with (arrow (S (S w)) 2 5) by lia.
    pose proof (arrow_ge4 (S (2 + w + 2 * p)) (arrow (S (S w)) 2 5) ltac:(lia)).
    revert H0. generalize (arrow (S (2 + w + 2 * p)) 2 (arrow (S (S w)) 2 5)). intros. lia. }
  rewrite Ef.
  unfold Per.
  follow (P1_B (4 + k) 1 (S (S w)) (1 + 3 * p)).
  follow (DEP9 (const 0%sym) (S w) (1 + 3 * p) (1 :: 0 :: 0 :: 0 :: repeat 1 1 ++ 5 :: repeat 2 (2 + (4 + k)))).
  rewrite Hx. replace (2 + (4 + k)) with (6 + k) by lia.
  follow (E_B k p (3 * x) w). rewrite merge3.
  replace (3 + 3 * x) with (0 + 3 * S x) by lia.
  rewrite <- (app_nil_r (repeat 1 (2 + w + 2 * p) ++ [0])), <- app_assoc.
  apply (CLR (2 + w + 2 * p) (S x) 0 [] (FarE k) 4 (or_intror r1_4)).
Qed.

(** ** The start with an explicit accumulator *)

Definition g0 : nat := arrow 35 2 (arrow 34 2 5 - 1).

Lemma reach_per_exact : c0 -->* Per 1 (6 * T - 19) 34 (3 * g0 - 8).
Proof.
  pose proof Af_closed as HAf. pose proof T_ge as HT. rewrite <- Af_def in HAf.
  remember (arrow 34 2 5 - 3) as x0 eqn:Ex0.
  assert (Hx0 : iter 3 (U 33) 4 = 1 + 3 * x0) by (rewrite Ex0; apply iterU_eq).
  assert (Hg0 : 3 * g0 - 8 = iter x0 (U 34) 4).
  { rewrite iterU_eq. unfold g0. rewrite Ex0. pose proof (arrow5 34).
    replace (arrow 34 2 5 - 3 + 2) with (arrow 34 2 5 - 1) by lia.
    pose proof (arrow_ge4 35 (arrow 34 2 5 - 1) ltac:(lia)).
    revert H0. generalize (arrow 35 2 (arrow 34 2 5 - 1)). intros. lia. }
  rewrite Hg0.
  follow init_reach.
  follow (CLR 35 2 1 [] (const 0%sym) 4 (or_intror r1_4)). rewrite <- Af_def.
  rewrite repeat_snoc, app_nil_r.
  follow (H_B 35 Af).
  replace (repeat 1 4 ++ repeat 1 (2 * Af) ++ [2]) with (repeat 1 (5 + (6 * T - 17)) ++ [2])
    by (rewrite <- repeat_add; f_equal; f_equal; revert HAf HT; generalize Af T; intros; lia).
  follow (S0_B (6 * T - 17) 33 6).
  follow (CLR 33 3 0 (0 :: 0 :: 0 :: repeat 1 (6 * T - 17) ++ [5; 2]) (const 0%sym) 4 (or_intror r1_4)).
  rewrite Hx0.
  replace (6 * T - 17) with (2 + (6 * T - 19)) by (revert HT; generalize T; intros; lia).
  follow (P4_B 1 (6 * T - 19) 0 (3 * x0) 32). rewrite merge3.
  apply (CLR (2 + 32 + 2 * 0) x0 2 _ (const 0%sym) 4 (or_intror r1_4)).
Qed.

Lemma g0_ge : F 34 <= g0.
Proof. unfold g0. rewrite <- arrow_S3. apply arrow_mono. pose proof (arrow5 34). lia. Qed.

(** ** The closed form *)

Definition fin : nat * nat := stepn JJ (34, g0).
Definition Wf : nat := fst fin + 2 * snd fin - 6.

(** the exact number of ones on the halting tape *)
Definition score_value : nat := 2 * Wf + 3 * arrow (S Wf) 2 (arrow (fst fin) 2 5) + 12 * JJ + 5.

Lemma JJ_closed : JJ = (3 * arrow 37 2 3 - 13) / 7.
Proof. unfold JJ. rewrite T_def. reflexivity. Qed.

Lemma fin_props : 3 <= fst fin /\ F (fst fin) <= snd fin /\ iter (2 * JJ) F 34 <= fst fin.
Proof.
  destruct (PERIODS_G JJ 1 34 g0 ltac:(lia) g0_ge) as [_ [H2 [H3 H4]]].
  unfold fin. split; [exact H2 | split; [exact H3 | exact H4]].
Qed.

Theorem score_closed : exists c, c0 -->* c /\ halted tm c /\ ones c score_value.
Proof.
  destruct JJ_eq as [HJ HJ1].
  pose proof g0_ge as Hg0. pose proof (F_ge 34) as HF34.
  destruct (PERIODS_G JJ 1 34 g0 ltac:(lia) Hg0) as [H1 [H2 [H3 H4]]].
  fold fin in H1, H2, H3, H4.
  pose proof (F_ge (fst fin)) as HFf.
  exists (c_halt (3 * arrow (S Wf) 2 (arrow (fst fin) 2 5) - 8) (4 * JJ - 3) Wf).
  split; [| split; [apply c_halt_halted |]].
  - pose proof reach_per_exact as H0. rewrite HJ in H0.
    follow H0.
    replace (4 * JJ + 1) with (4 + (4 * JJ - 3)) in H1 by lia.
    follow H1.
    follow (ENDGAME_G (4 * JJ - 3) (fst fin) (snd fin) H2 ltac:(lia)).
    apply HALT_exact.
  - pose proof (ones_c_halt (3 * arrow (S Wf) 2 (arrow (fst fin) 2 5) - 8) (4 * JJ - 3) Wf) as HO.
    unfold score_value.
    pose proof (arrow_ge4 (S Wf) (arrow (fst fin) 2 5) ltac:(pose proof (arrow5 (fst fin)); lia)) as HA.
    revert HO HA. generalize (arrow (S Wf) 2 (arrow (fst fin) 2 5)). intros A HO HA.
    replace (2 * Wf + 3 * A + 12 * JJ + 5) with (2 * Wf + (3 * A - 8) + 3 * (4 * JJ - 3) + 22) by lia.
    exact HO.
Qed.

(** the closed form exceeds the lower bound of BB10_n1_bound.v *)
Theorem score_value_gt : iter (2 * JJ + 1) F 34 < score_value.
Proof.
  destruct fin_props as [H1 [H2 H3]].
  pose proof (iterF_mono 1 _ _ H3) as H4. rewrite <- iter_add in H4. replace (1 + 2 * JJ) with (2 * JJ + 1) in H4 by lia.
  change (iter 1 F (fst fin)) with (F (fst fin)) in H4.
  unfold score_value, Wf.
  revert H2 H4. generalize (iter (2 * JJ + 1) F 34) (arrow (S (fst fin + 2 * snd fin - 6)) 2 (arrow (fst fin) 2 5)).
  intros. pose proof (F_ge (fst fin)). lia.
Qed.

(** the closed form, with every definition unfolded down to arrow, stepn and T *)
Theorem score_closed_unfolded : exists c, c0 -->* c /\ halted tm c /\
  ones c (let J := (3 * arrow 37 2 3 - 13) / 7 in
          let s := stepn J (34, arrow 35 2 (arrow 34 2 5 - 1)) in
          let W := fst s + 2 * snd s - 6 in
          2 * W + 3 * arrow (S W) 2 (arrow (fst s) 2 5) + 12 * J + 5).
Proof.
  destruct score_closed as [c [H1 [H2 H3]]]. exists c. split; [exact H1 | split; [exact H2 |]].
  rewrite <- JJ_closed. exact H3.
Qed.

Print Assumptions score_closed.
Print Assumptions score_closed_unfolded.
Print Assumptions score_value_gt.
