(** * BB(10) candidate 1RB0RA_1LC1LF_1RD0LB_1RA1LE_0LJ0LC_1RG1LD_0RI0RH_1RG1LF_1RE1RI_---1LC halts *)

(** Generated by bb8_list/autoproof (engine.py: symbolic execution with automatic loop lemmas; coqgen.py). *)

(** Machine-checked halting proof (bb8_list/investigations/bb10_lead_0LJ0LC.md).  Generated by
    bb8_list/investigations/bb10_lead_0LJ0LC/coq/gen_final.py: the machine-level lemmas of Part 1 come from the
    symbolic explorer (mexp.py, autoproof engine; waypoints in parts2.py), Parts 2-3 (glue.v.in) are hand-written.

    Family (head in G on the blank right of the word; the word read from the left):
      N a k g l = 0^inf .. l .. (10)^g 1 ((10) 1)^k (10)^a 1 G> 0^inf
    i.e. an accumulator of a units (a = 2b+1 for the counter b), k zero digits ((10) 1, one unit), then a group of
    g units (a digit d has g = 2d+1; the top entry of a rebuilt list has an even number of units), then the rest.
    Rules (all parameters):
      NR1   : N a 0 (n+2) l                  -->* N (a+4) 0 n l                               (b -> b+2)
      NR23  : N a (k+1) (n+3) (1 l)          -->* N 1 k (a+4) ((10)^(n+1) 1 l)              (borrow, b -> 0)
      NR23z : N a (k+1) 2 (1 0^inf)          -->* N 1 k (a+4) (1 1 0^inf)                   (top entry 2 -> 0)
      REBUILD: all M+2 digits zero           -->* N 1 (2a+M+6) 6 (1 0^inf)                   (top entry 6)
      HALTN : N a (L+2) 0 (1 0^inf)          -->* cH a (L+1), J reads 0 (J0 undefined)
    Clearing: F 0 b = b+2, F (k+1) b = (F k)^(b+2) (0); a digit with u units at depth k maps b to (F k)^u b.
    Run: blank -> N 1 26 5 (step 3890) -> exhausted list of 27 zero digits with b_f = (F 26)^2 0
         -> rebuilt list: top entry 6 over L = 4 b_f + 33 zero digits -> b_2 = (F L)^3 0 -> halt. *)

From BB8 Require Import Individual102.
From Coq Require Import Lia PeanoNat List.
Import ListNotations.
Set Default Goal Selector "!".

(* machine: 1RB0RA_1LC1LF_1RD0LB_1RA1LE_0LJ0LC_1RG1LD_0RI0RH_1RG1LF_1RE1RI_---1LC *)
Definition tm : TM := fun '(q, s) =>
  match q, s with
  | A, 0 => Some (1, R, B)  | A, 1 => Some (0, R, A)
  | B, 0 => Some (1, L, C)  | B, 1 => Some (1, L, F)
  | C, 0 => Some (1, R, D)  | C, 1 => Some (0, L, B)
  | D, 0 => Some (1, R, A)  | D, 1 => Some (1, L, E)
  | E, 0 => Some (0, L, J)  | E, 1 => Some (0, L, C)
  | F, 0 => Some (1, R, G)  | F, 1 => Some (1, L, D)
  | G, 0 => Some (0, R, I)  | G, 1 => Some (0, R, H)
  | H, 0 => Some (1, R, G)  | H, 1 => Some (1, L, F)
  | I, 0 => Some (1, R, E)  | I, 1 => Some (1, R, I)
  | J, 0 => None            | J, 1 => Some (1, L, C)
  end.

Notation "c --> c'" := (c -[ tm ]-> c')   (at level 40).
Notation "c -->* c'" := (c -[ tm ]->* c') (at level 40).
Notation "c -->+ c'" := (c -[ tm ]->+ c') (at level 40).

(** ** Tape normalization (as in the hand-written proofs, e.g. BB8_048631_1RB0RG.v) *)

Lemma align_lpow : forall (x : Sym) xs ys n,
  (x::xs)^^n *> x >> ys = x >> (xs ++ [x])^^n *> ys.
Proof.
  induction n.
  - reflexivity.
  - simpl. repeat rewrite Str_app_assoc. rewrite IHn. reflexivity.
Qed.

Lemma align_lpow_const : forall (x : Sym) xs n,
  (x::xs)^^n *> const x = x >> (xs ++ [x])^^n *> const x.
Proof. intros. rewrite const_unfold at 1. apply align_lpow. Qed.

Ltac align_tape := repeat ((rewrite align_lpow || rewrite align_lpow_const); simpl app).
Ltac norm_nat := repeat progress (rewrite ?Nat.add_succ_r, ?Nat.add_0_r; simpl).
(** Adjacent powers of the same block, in either order (crossing a run pushes its powers in reverse order). *)
Lemma lpow_merge : forall (xs : list Sym) n m Y, xs^^n *> xs^^m *> Y = xs^^(n + m) *> Y.
Proof. intros. rewrite lpow_add, Str_app_assoc. reflexivity. Qed.

(** Blank cells in front of the blank tail. *)
Lemma zero_const : (0 >> const 0 : side) = const 0.
Proof. symmetry. apply const_unfold. Qed.

Ltac finish_norm := apply evstep_refl'; norm_nat; align_tape; repeat rewrite lpow_merge; repeat rewrite zero_const;
  try reflexivity; lia_refl.

Lemma lpow_snoc : forall (xs : list Sym) n Y, xs^^(S n) *> Y = xs^^n *> xs *> Y.
Proof. intros. simpl. rewrite <- lpow_shift. apply Str_app_assoc. Qed.

Lemma cr_BL_01_01 : forall n l r, [0;1]^^n *> l <{{B}} r -->* l <{{B}} [0;1]^^n *> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.

Lemma cr_HR_01_01 : forall n l r, l {{H}}> [0;1]^^n *> r -->* [0;1]^^n *> l {{H}}> r.
Proof. induction n; intros. - finish. - execute. follow IHn. finish_norm. Qed.


Lemma R1_st1 : forall a n l, (1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> l) {{G}}> (const 0) -->* (1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 0 >> 1 >> 0 >> 1 >> 1 >> [0;1]^^n *> l) {{G}}> (const 0).
Proof.
  intros. do 8 step. follow cr_BL_01_01. do 3 step. follow cr_HR_01_01. do 9 step.
  follow cr_BL_01_01. do 7 step. follow cr_HR_01_01. do 5 step. finish_norm.
Qed.

Lemma R2_st1 : forall a n l, (1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{G}}> (const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> ([1;0]^^a *> const 0).
Proof.
  intros. do 8 step. follow cr_BL_01_01. do 3 step. follow cr_HR_01_01. do 9 step.
  follow cr_BL_01_01. do 13 step. repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow_const 0 [1]). simpl app. do 1 step. finish_norm.
Qed.

Lemma R2_st3 : forall i2 n n3 l, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i2 *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> (1 >> 0 >> [1;0]^^n3 *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i2 *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> ([1;0]^^n3 *> const 0).
Proof.
  intros. do 6 step. finish_norm.
Qed.

Lemma R2_round2 : forall n3 i2 n l, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i2 *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> (1 >> 0 >> [1;0]^^n3 *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i2 *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> ([1;0]^^n3 *> const 0).
Proof.
  intros. follow R2_st3. finish_norm.
Qed.

Lemma R2_loop4 : forall n1 i2 n l, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i2 *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> ([1;0]^^n1 *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i2 *> [0;1]^^n1 *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> (const 0).
Proof.
  induction n1; intros.
  - finish_norm.
  - follow (R2_round2 n1 i2 n l).
    follow (IHn1 (S i2) n l).
    finish_norm.
Qed.

Lemma R2_loop4_z : forall a n l, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> ([1;0]^^a *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> (const 0).
Proof.
  intros. follow (R2_loop4 a 0 n l). finish_norm.
Qed.

Lemma R2_st5 : forall a n l, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> (const 0) -->* (1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 0 >> 1 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{G}}> (const 0).
Proof.
  intros. do 13 step. follow cr_BL_01_01. do 3 step. follow cr_HR_01_01. do 16 step. finish_norm.
Qed.

Lemma R2z_st1 : forall a, (1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> const 0) {{G}}> (const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> ([1;0]^^a *> const 0).
Proof.
  intros. do 8 step. follow cr_BL_01_01. do 3 step. follow cr_HR_01_01. do 9 step.
  follow cr_BL_01_01. do 13 step. repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow_const 0 [1]). simpl app. do 1 step. finish_norm.
Qed.

Lemma R2z_st3 : forall i6 n7, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i6 *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> (1 >> 0 >> [1;0]^^n7 *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i6 *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> ([1;0]^^n7 *> const 0).
Proof.
  intros. do 6 step. finish_norm.
Qed.

Lemma R2z_round2 : forall n7 i6, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i6 *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> (1 >> 0 >> [1;0]^^n7 *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i6 *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> ([1;0]^^n7 *> const 0).
Proof.
  intros. follow R2z_st3. finish_norm.
Qed.

Lemma R2z_loop4 : forall n5 i6, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i6 *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> ([1;0]^^n5 *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i6 *> [0;1]^^n5 *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> (const 0).
Proof.
  induction n5; intros.
  - finish_norm.
  - follow (R2z_round2 n5 i6).
    follow (IHn5 (S i6)).
    finish_norm.
Qed.

Lemma R2z_loop4_z : forall a, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> ([1;0]^^a *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> (const 0).
Proof.
  intros. follow (R2z_loop4 a 0). finish_norm.
Qed.

Lemma R2z_st5 : forall a, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> (const 0) -->* (1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 0 >> 1 >> 1 >> 1 >> const 0) {{G}}> (const 0).
Proof.
  intros. do 13 step. follow cr_BL_01_01. do 3 step. follow cr_HR_01_01. do 16 step. finish_norm.
Qed.

Lemma PRE_st1 : forall a k P, (1 >> [0;1]^^a *> [1;0;1]^^k *> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> P) {{G}}> (const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 1 >> [0;1;1]^^k *> P) {{B}}> ([1;0]^^a *> const 0).
Proof.
  intros. do 8 step. follow cr_BL_01_01. repeat rewrite (align_lpow 1 [0;1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 0 [1;1]). simpl app. do 2 step. follow cr_HR_01_01. do 9 step.
  follow cr_BL_01_01. do 2 step. repeat rewrite (align_lpow 1 [1;0]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0;1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 0 [1;1]). simpl app. do 9 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow_const 0 [1]). simpl app. do 1 step. finish_norm.
Qed.

Lemma PRE_st3 : forall i10 k n11 P, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i10 *> 1 >> 1 >> [0;1;1]^^k *> P) {{B}}> (1 >> 0 >> [1;0]^^n11 *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i10 *> 1 >> 1 >> [0;1;1]^^k *> P) {{B}}> ([1;0]^^n11 *> const 0).
Proof.
  intros. do 6 step. finish_norm.
Qed.

Lemma PRE_round2 : forall n11 i10 k P, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i10 *> 1 >> 1 >> [0;1;1]^^k *> P) {{B}}> (1 >> 0 >> [1;0]^^n11 *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i10 *> 1 >> 1 >> [0;1;1]^^k *> P) {{B}}> ([1;0]^^n11 *> const 0).
Proof.
  intros. follow PRE_st3. finish_norm.
Qed.

Lemma PRE_loop4 : forall n9 i10 k P, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i10 *> 1 >> 1 >> [0;1;1]^^k *> P) {{B}}> ([1;0]^^n9 *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i10 *> [0;1]^^n9 *> 1 >> 1 >> [0;1;1]^^k *> P) {{B}}> (const 0).
Proof.
  induction n9; intros.
  - finish_norm.
  - follow (PRE_round2 n9 i10 k P).
    follow (IHn9 (S i10) k P).
    finish_norm.
Qed.

Lemma PRE_loop4_z : forall a k P, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 1 >> [0;1;1]^^k *> P) {{B}}> ([1;0]^^a *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> [0;1;1]^^k *> P) {{B}}> (const 0).
Proof.
  intros. follow (PRE_loop4 a 0 k P). finish_norm.
Qed.

Lemma PRE_st5 : forall a k P, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> [0;1;1]^^k *> P) {{B}}> (const 0) -->* (1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> [0;1;1]^^k *> P) <{{E}} (1 >> 0 >> 1 >> const 0).
Proof.
  intros. do 5 step. finish_norm.
Qed.

Lemma WALK_st1 : forall a i j P, (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> 0 >> 1 >> 1 >> [0;1;1]^^j *> P) {{E}}> (1 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 1 >> [0;1;1]^^j *> P) {{B}}> ([1;0]^^a *> 0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. do 8 step. follow cr_BL_01_01. do 5 step. repeat rewrite (align_lpow 0 [1]). simpl app.
  do 1 step. repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step. finish_norm.
Qed.

Lemma WALK_st3 : forall i i14 j n15 P, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i14 *> 1 >> 1 >> [0;1;1]^^j *> P) {{B}}> (1 >> 0 >> [1;0]^^n15 *> 0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i14 *> 1 >> 1 >> [0;1;1]^^j *> P) {{B}}> ([1;0]^^n15 *> 0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. do 6 step. finish_norm.
Qed.

Lemma WALK_round2 : forall n15 i14 i j P, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i14 *> 1 >> 1 >> [0;1;1]^^j *> P) {{B}}> (1 >> 0 >> [1;0]^^n15 *> 0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i14 *> 1 >> 1 >> [0;1;1]^^j *> P) {{B}}> ([1;0]^^n15 *> 0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. follow WALK_st3. finish_norm.
Qed.

Lemma WALK_loop4 : forall n13 i14 i j P, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i14 *> 1 >> 1 >> [0;1;1]^^j *> P) {{B}}> ([1;0]^^n13 *> 0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i14 *> [0;1]^^n13 *> 1 >> 1 >> [0;1;1]^^j *> P) {{B}}> (0 >> [1;0;1]^^i *> const 0).
Proof.
  induction n13; intros.
  - finish_norm.
  - follow (WALK_round2 n13 i14 i j P).
    follow (IHn13 (S i14) i j P).
    finish_norm.
Qed.

Lemma WALK_loop4_z : forall a i j P, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 1 >> [0;1;1]^^j *> P) {{B}}> ([1;0]^^a *> 0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> [0;1;1]^^j *> P) {{B}}> (0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. follow (WALK_loop4 a 0 i j P). finish_norm.
Qed.

Lemma WALK_st5 : forall a i j P, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> [0;1;1]^^j *> P) {{B}}> (0 >> [1;0;1]^^i *> const 0) -->* (1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> [0;1;1]^^j *> P) <{{E}} (1 >> 0 >> 1 >> [1;0;1]^^i *> const 0).
Proof.
  intros. do 5 step. finish_norm.
Qed.

Lemma BOR_st1 : forall a k n l, (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{E}}> (1 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> ([1;0]^^a *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. do 8 step. follow cr_BL_01_01. do 5 step. repeat rewrite (align_lpow 0 [1]). simpl app.
  do 1 step. repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step. finish_norm.
Qed.

Lemma BOR_st3 : forall i18 k n n19 l, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i18 *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> (1 >> 0 >> [1;0]^^n19 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i18 *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> ([1;0]^^n19 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. do 6 step. finish_norm.
Qed.

Lemma BOR_round2 : forall n19 i18 k n l, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i18 *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> (1 >> 0 >> [1;0]^^n19 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i18 *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> ([1;0]^^n19 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. follow BOR_st3. finish_norm.
Qed.

Lemma BOR_loop4 : forall n17 i18 k n l, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i18 *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> ([1;0]^^n17 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i18 *> [0;1]^^n17 *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> (0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  induction n17; intros.
  - finish_norm.
  - follow (BOR_round2 n17 i18 k n l).
    follow (IHn17 (S i18) k n l).
    finish_norm.
Qed.

Lemma BOR_loop4_z : forall a k n l, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> ([1;0]^^a *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> (0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. follow (BOR_loop4 a 0 k n l). finish_norm.
Qed.

Lemma BOR_st5 : forall a k n l, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{B}}> (0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 0 >> 1 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{G}}> (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. do 13 step. follow cr_BL_01_01. do 3 step. follow cr_HR_01_01. do 14 step. finish_norm.
Qed.

Lemma BORz_st1 : forall a k, (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> const 0) {{E}}> (1 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> ([1;0]^^a *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. do 8 step. follow cr_BL_01_01. do 5 step. repeat rewrite (align_lpow 0 [1]). simpl app.
  do 1 step. repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step. finish_norm.
Qed.

Lemma BORz_st3 : forall i22 k n23, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i22 *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> (1 >> 0 >> [1;0]^^n23 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i22 *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> ([1;0]^^n23 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. do 6 step. finish_norm.
Qed.

Lemma BORz_round2 : forall n23 i22 k, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i22 *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> (1 >> 0 >> [1;0]^^n23 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i22 *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> ([1;0]^^n23 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. follow BORz_st3. finish_norm.
Qed.

Lemma BORz_loop4 : forall n21 i22 k, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i22 *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> ([1;0]^^n21 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i22 *> [0;1]^^n21 *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> (0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  induction n21; intros.
  - finish_norm.
  - follow (BORz_round2 n21 i22 k).
    follow (IHn21 (S i22) k).
    finish_norm.
Qed.

Lemma BORz_loop4_z : forall a k, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> ([1;0]^^a *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> (0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. follow (BORz_loop4 a 0 k). finish_norm.
Qed.

Lemma BORz_st5 : forall a k, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 1 >> const 0) {{B}}> (0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 0 >> 1 >> 1 >> 1 >> const 0) {{G}}> (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. do 13 step. follow cr_BL_01_01. do 3 step. follow cr_HR_01_01. do 14 step. finish_norm.
Qed.

Lemma BORn_st1 : forall a k, (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> const 0) {{E}}> (1 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> const 0) {{B}}> ([1;0]^^a *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. do 8 step. follow cr_BL_01_01. do 5 step. repeat rewrite (align_lpow 0 [1]). simpl app.
  do 1 step. repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step. finish_norm.
Qed.

Lemma BORn_st3 : forall i26 k n27, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i26 *> 1 >> 0 >> 1 >> const 0) {{B}}> (1 >> 0 >> [1;0]^^n27 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i26 *> 1 >> 0 >> 1 >> const 0) {{B}}> ([1;0]^^n27 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. do 6 step. finish_norm.
Qed.

Lemma BORn_round2 : forall n27 i26 k, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i26 *> 1 >> 0 >> 1 >> const 0) {{B}}> (1 >> 0 >> [1;0]^^n27 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i26 *> 1 >> 0 >> 1 >> const 0) {{B}}> ([1;0]^^n27 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. follow BORn_st3. finish_norm.
Qed.

Lemma BORn_loop4 : forall n25 i26 k, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i26 *> 1 >> 0 >> 1 >> const 0) {{B}}> ([1;0]^^n25 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i26 *> [0;1]^^n25 *> 1 >> 0 >> 1 >> const 0) {{B}}> (0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  induction n25; intros.
  - finish_norm.
  - follow (BORn_round2 n25 i26 k).
    follow (IHn25 (S i26) k).
    finish_norm.
Qed.

Lemma BORn_loop4_z : forall a k, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> const 0) {{B}}> ([1;0]^^a *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 0 >> 1 >> const 0) {{B}}> (0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. follow (BORn_loop4 a 0 k). finish_norm.
Qed.

Lemma BORn_st5 : forall a k, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 0 >> 1 >> const 0) {{B}}> (0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 0 >> 1 >> 1 >> const 0) {{G}}> (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros. do 13 step. follow cr_BL_01_01. do 3 step. follow cr_HR_01_01. do 14 step. finish_norm.
Qed.

Lemma RET_st1 : forall i j T, (1 >> 1 >> [0;1;1]^^i *> T) {{G}}> (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^j *> const 0) -->* (1 >> 1 >> 0 >> 1 >> 1 >> [0;1;1]^^i *> T) {{G}}> (1 >> 0 >> 0 >> [1;0;1]^^j *> const 0).
Proof.
  intros. do 9 step. finish_norm.
Qed.

Lemma END_st1 : forall a k T, (1 >> 1 >> 0 >> 1 >> 1 >> [0;1;1]^^k *> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> T) {{G}}> (1 >> 0 >> 0 >> const 0) -->* (1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> [0;1;1]^^k *> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> T) {{G}}> (const 0).
Proof.
  intros. do 2 step. finish_norm.
Qed.

Lemma LASTW_st1 : forall a i, (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> const 0) {{E}}> (1 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> const 0) {{B}}> ([1;0]^^a *> 0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. do 8 step. follow cr_BL_01_01. do 5 step. repeat rewrite (align_lpow 0 [1]). simpl app.
  do 1 step. repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step.
  repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step. finish_norm.
Qed.

Lemma LASTW_st3 : forall i i30 n31, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i30 *> const 0) {{B}}> (1 >> 0 >> [1;0]^^n31 *> 0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i30 *> const 0) {{B}}> ([1;0]^^n31 *> 0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. do 6 step. finish_norm.
Qed.

Lemma LASTW_round2 : forall n31 i30 i, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i30 *> const 0) {{B}}> (1 >> 0 >> [1;0]^^n31 *> 0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i30 *> const 0) {{B}}> ([1;0]^^n31 *> 0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. follow LASTW_st3. finish_norm.
Qed.

Lemma LASTW_loop4 : forall n29 i30 i, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i30 *> const 0) {{B}}> ([1;0]^^n29 *> 0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i30 *> [0;1]^^n29 *> const 0) {{B}}> (0 >> [1;0;1]^^i *> const 0).
Proof.
  induction n29; intros.
  - finish_norm.
  - follow (LASTW_round2 n29 i30 i).
    follow (IHn29 (S i30) i).
    finish_norm.
Qed.

Lemma LASTW_loop4_z : forall a i, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> const 0) {{B}}> ([1;0]^^a *> 0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> const 0) {{B}}> (0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. follow (LASTW_loop4 a 0 i). finish_norm.
Qed.

Lemma LASTW_st5 : forall a i, (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> const 0) {{B}}> (0 >> [1;0;1]^^i *> const 0) -->* (1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> const 0) <{{E}} (1 >> 0 >> 1 >> [1;0;1]^^i *> const 0).
Proof.
  intros. do 5 step. finish_norm.
Qed.

Lemma YC_st1 : forall i u, (1 >> 0 >> 1 >> [0;1]^^u *> const 0) {{E}}> (1 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 1 >> 1 >> const 0) {{B}}> ([1;0]^^u *> 0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. do 4 step. follow cr_BL_01_01. do 7 step. repeat rewrite (align_lpow 0 [1]). simpl app.
  do 1 step. repeat rewrite (align_lpow 1 [0]). simpl app. do 5 step.
  repeat rewrite (align_lpow 0 [1]). simpl app. do 1 step. finish_norm.
Qed.

Lemma YC_st3 : forall i i34 n35, (1 >> 0 >> 0 >> 1 >> [0;1]^^i34 *> 1 >> 1 >> const 0) {{B}}> (1 >> 0 >> [1;0]^^n35 *> 0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i34 *> 1 >> 1 >> const 0) {{B}}> ([1;0]^^n35 *> 0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. do 6 step. finish_norm.
Qed.

Lemma YC_round2 : forall n35 i34 i, (1 >> 0 >> 0 >> 1 >> [0;1]^^i34 *> 1 >> 1 >> const 0) {{B}}> (1 >> 0 >> [1;0]^^n35 *> 0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i34 *> 1 >> 1 >> const 0) {{B}}> ([1;0]^^n35 *> 0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. follow YC_st3. finish_norm.
Qed.

Lemma YC_loop4 : forall n33 i34 i, (1 >> 0 >> 0 >> 1 >> [0;1]^^i34 *> 1 >> 1 >> const 0) {{B}}> ([1;0]^^n33 *> 0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> [0;1]^^i34 *> [0;1]^^n33 *> 1 >> 1 >> const 0) {{B}}> (0 >> [1;0;1]^^i *> const 0).
Proof.
  induction n33; intros.
  - finish_norm.
  - follow (YC_round2 n33 i34 i).
    follow (IHn33 (S i34) i).
    finish_norm.
Qed.

Lemma YC_loop4_z : forall i u, (1 >> 0 >> 0 >> 1 >> 1 >> 1 >> const 0) {{B}}> ([1;0]^^u *> 0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> [0;1]^^u *> 1 >> 1 >> const 0) {{B}}> (0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. follow (YC_loop4 u 0 i). finish_norm.
Qed.

Lemma YC_st5 : forall i u, (1 >> 0 >> 0 >> 1 >> [0;1]^^u *> 1 >> 1 >> const 0) {{B}}> (0 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> const 0) {{B}}> ([1;0]^^u *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0).
Proof.
  intros. do 7 step. follow cr_BL_01_01. do 5 step. repeat rewrite (align_lpow 0 [1]). simpl app.
  do 1 step. finish_norm.
Qed.

Lemma YC_st7 : forall i i38 n39, (1 >> 0 >> 0 >> 1 >> [0;1]^^i38 *> const 0) {{B}}> (1 >> 0 >> [1;0]^^n39 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i38 *> const 0) {{B}}> ([1;0]^^n39 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0).
Proof.
  intros. do 6 step. finish_norm.
Qed.

Lemma YC_round6 : forall n39 i38 i, (1 >> 0 >> 0 >> 1 >> [0;1]^^i38 *> const 0) {{B}}> (1 >> 0 >> [1;0]^^n39 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^i38 *> const 0) {{B}}> ([1;0]^^n39 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0).
Proof.
  intros. follow YC_st7. finish_norm.
Qed.

Lemma YC_loop8 : forall n37 i38 i, (1 >> 0 >> 0 >> 1 >> [0;1]^^i38 *> const 0) {{B}}> ([1;0]^^n37 *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> [0;1]^^i38 *> [0;1]^^n37 *> const 0) {{B}}> (0 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0).
Proof.
  induction n37; intros.
  - finish_norm.
  - follow (YC_round6 n37 i38 i).
    follow (IHn37 (S i38) i).
    finish_norm.
Qed.

Lemma YC_loop8_z : forall i u, (1 >> 0 >> 0 >> 1 >> const 0) {{B}}> ([1;0]^^u *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 0 >> 1 >> [0;1]^^u *> const 0) {{B}}> (0 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0).
Proof.
  intros. follow (YC_loop8 u 0 i). finish_norm.
Qed.

Lemma YC_st9 : forall i u, (1 >> 0 >> 0 >> 1 >> [0;1]^^u *> const 0) {{B}}> (0 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0) -->* (1 >> 1 >> [0;1]^^u *> const 0) <{{E}} (1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0).
Proof.
  intros. do 5 step. finish_norm.
Qed.

Lemma YEND_st1 : forall i, (1 >> const 0) {{E}}> (1 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0) -->* (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> const 0) {{H}}> ([1;0;1]^^i *> const 0).
Proof.
  intros. do 26 step. finish_norm.
Qed.

Lemma YEND_st3 : forall i42 n43, (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^i42 *> 0 >> 1 >> const 0) {{H}}> (1 >> 0 >> 1 >> [1;0;1]^^n43 *> const 0) -->* (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^i42 *> 0 >> 1 >> const 0) {{H}}> ([1;0;1]^^n43 *> const 0).
Proof.
  intros. do 5 step. finish_norm.
Qed.

Lemma YEND_round2 : forall n43 i42, (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^i42 *> 0 >> 1 >> const 0) {{H}}> (1 >> 0 >> 1 >> [1;0;1]^^n43 *> const 0) -->* (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^i42 *> 0 >> 1 >> const 0) {{H}}> ([1;0;1]^^n43 *> const 0).
Proof.
  intros. follow YEND_st3. finish_norm.
Qed.

Lemma YEND_loop4 : forall n41 i42, (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^i42 *> 0 >> 1 >> const 0) {{H}}> ([1;0;1]^^n41 *> const 0) -->* (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^i42 *> [1;0;1]^^n41 *> 0 >> 1 >> const 0) {{H}}> (const 0).
Proof.
  induction n41; intros.
  - finish_norm.
  - follow (YEND_round2 n41 i42).
    follow (IHn41 (S i42)).
    finish_norm.
Qed.

Lemma YEND_loop4_z : forall i, (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> const 0) {{H}}> ([1;0;1]^^i *> const 0) -->* (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> 0 >> 1 >> const 0) {{H}}> (const 0).
Proof.
  intros. follow (YEND_loop4 i 0). finish_norm.
Qed.

Lemma YEND_st5 : forall i, (0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> 0 >> 1 >> const 0) {{H}}> (const 0) -->* (1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> 0 >> 1 >> const 0) {{G}}> (const 0).
Proof.
  intros. do 1 step. finish_norm.
Qed.

Lemma HEND_st1 : forall a i, (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> 1 >> const 0) {{E}}> (1 >> [1;0;1]^^i *> const 0) -->* (const 0) <{{J}} (0 >> 1 >> 1 >> 1 >> [0;1]^^a *> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 0 >> [1;0;1]^^i *> const 0).
Proof.
  intros. do 8 step. follow cr_BL_01_01. do 4 step. finish_norm.
Qed.

Lemma R1 : forall a n l, (1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> l) {{G}}> (const 0) -->* (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> [0;1]^^n *> l) {{G}}> (const 0).
Proof.
  intros.
  follow R1_st1.
  finish_norm.
Qed.

Lemma R2 : forall a n l (Hpos_a : 0 < a), (1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{G}}> (const 0) -->* (1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{G}}> (const 0).
Proof.
  intros.
  follow R2_st1.
  follow R2_loop4_z.
  follow R2_st5.
  finish_norm.
Qed.

Lemma R2z : forall a (Hpos_a : 0 < a), (1 >> [0;1]^^a *> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> const 0) {{G}}> (const 0) -->* (1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> const 0) {{G}}> (const 0).
Proof.
  intros.
  follow R2z_st1.
  follow R2z_loop4_z.
  follow R2z_st5.
  finish_norm.
Qed.

Lemma PRE : forall a k P (Hpos_a : 0 < a), (1 >> [0;1]^^a *> [1;0;1]^^k *> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 1 >> P) {{G}}> (const 0) -->* (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> [0;1;1]^^k *> P) {{E}}> (1 >> 1 >> 0 >> 1 >> const 0).
Proof.
  intros.
  follow PRE_st1.
  follow PRE_loop4_z.
  follow PRE_st5.
  finish_norm.
Qed.

Lemma WALK : forall a i j P (Hpos_a : 0 < a), (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> 0 >> 1 >> 1 >> [0;1;1]^^j *> P) {{E}}> (1 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> [0;1;1]^^j *> P) {{E}}> (1 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0).
Proof.
  intros.
  follow WALK_st1.
  follow WALK_loop4_z.
  follow WALK_st5.
  finish_norm.
Qed.

Lemma BOR : forall a k n l (Hpos_a : 0 < a), (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{E}}> (1 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 0 >> 1 >> [0;1]^^n *> 1 >> l) {{G}}> (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros.
  follow BOR_st1.
  follow BOR_loop4_z.
  follow BOR_st5.
  finish_norm.
Qed.

Lemma BORz : forall a k (Hpos_a : 0 < a), (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> const 0) {{E}}> (1 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> const 0) {{G}}> (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros.
  follow BORz_st1.
  follow BORz_loop4_z.
  follow BORz_st5.
  finish_norm.
Qed.

Lemma BORn : forall a k (Hpos_a : 0 < a), (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> const 0) {{E}}> (1 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0) -->* (1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> const 0) {{G}}> (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^k *> const 0).
Proof.
  intros.
  follow BORn_st1.
  follow BORn_loop4_z.
  follow BORn_st5.
  finish_norm.
Qed.

Lemma RET : forall i j T, (1 >> 1 >> [0;1;1]^^i *> T) {{G}}> (1 >> 0 >> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^j *> const 0) -->* (1 >> 1 >> 0 >> 1 >> 1 >> [0;1;1]^^i *> T) {{G}}> (1 >> 0 >> 0 >> [1;0;1]^^j *> const 0).
Proof.
  intros.
  follow RET_st1.
  finish_norm.
Qed.

Lemma END : forall a k T, (1 >> 1 >> 0 >> 1 >> 1 >> [0;1;1]^^k *> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> T) {{G}}> (1 >> 0 >> 0 >> const 0) -->* (1 >> 0 >> 1 >> [1;0;1]^^k *> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> T) {{G}}> (const 0).
Proof.
  intros.
  follow END_st1.
  finish_norm.
Qed.

Lemma LASTW : forall a i (Hpos_a : 0 < a), (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> const 0) {{E}}> (1 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> const 0) {{E}}> (1 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0).
Proof.
  intros.
  follow LASTW_st1.
  follow LASTW_loop4_z.
  follow LASTW_st5.
  finish_norm.
Qed.

Lemma YC : forall i u, (1 >> 0 >> 1 >> [0;1]^^u *> const 0) {{E}}> (1 >> [1;0;1]^^i *> const 0) -->* (1 >> [0;1]^^u *> const 0) {{E}}> (1 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0).
Proof.
  intros.
  follow YC_st1.
  follow YC_loop4_z.
  follow YC_st5.
  follow YC_loop8_z.
  follow YC_st9.
  finish_norm.
Qed.

Lemma YEND : forall i, (1 >> const 0) {{E}}> (1 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> const 0) -->* (1 >> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^i *> 1 >> 0 >> 1 >> 0 >> 1 >> const 0) {{G}}> (const 0).
Proof.
  intros.
  follow YEND_st1.
  follow YEND_loop4_z.
  follow YEND_st5.
  finish_norm.
Qed.

Lemma HEND : forall a i (Hpos_a : 0 < a), exists c, (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> 1 >> const 0) {{E}}> (1 >> [1;0;1]^^i *> const 0) -->* c /\ halted tm c.
Proof.
  intros. eexists. split.
  - apply HEND_st1.
  - simpl. reflexivity.
Qed.




(** * Part 2: the n-list family and its rules (hand-written glue over the generated lemmas above) *)

Lemma pow_S : forall (xs : list Sym) n Y, xs^^(S n) *> Y = xs *> xs^^n *> Y.
Proof. intros. simpl. apply Str_app_assoc. Qed.

Lemma zeros_snoc : forall k X, [1;0;1]^^(S k) *> X = [1;0;1]^^k *> 1 >> 0 >> 1 >> X.
Proof. intros. rewrite lpow_snoc. reflexivity. Qed.

Lemma zeros_snoc2 : forall k X, [1;0;1]^^(S (S k)) *> X = [1;0;1]^^k *> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> X.
Proof. intros. rewrite !lpow_snoc. reflexivity. Qed.

(** One group (10)^n 1 of the word, read from the head side: 1 (01)^n. *)
Definition grp (n : nat) (l : side) : side := 1 >> [0;1]^^n *> l.

(** N a k g l = 0^inf .. l .. (10)^g 1 ((10) 1)^k (10)^a 1 G> 0^inf : accumulator with a units, k zero digits
    (one unit each), then a group with g units, then the rest l of the word (read from the head side). *)
Definition N (a k g : nat) (l : side) : Q * tape := (grp a ([1;0;1]^^k *> grp g l)) {{G}}> const 0.

(** Walk / return / left-end shapes of the generated lemmas. *)
Definition Wc (a j i : nat) (P : side) : Q * tape :=
  (1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> 1 >> [0;1;1]^^j *> P) {{E}}> (1 >> [1;0;1]^^i *> const 0).
Definition Rc (i j : nat) (T : side) : Q * tape :=
  (1 >> 1 >> [0;1;1]^^i *> T) {{G}}> (1 >> 0 >> 0 >> [1;0;1]^^j *> const 0).
Definition Yc (u i : nat) : Q * tape := (1 >> [0;1]^^u *> const 0) {{E}}> (1 >> [1;0;1]^^i *> const 0).

Lemma WALKS : forall j a i P, 0 < a -> Wc a j i P -->* Wc a 0 (j + i) P.
Proof.
  induction j; intros a i P Ha.
  - apply evstep_refl.
  - eapply evstep_trans; [exact (WALK a i j P Ha) |].
    replace (S j + i) with (j + S i) by lia. exact (IHj a (S i) P Ha).
Qed.

Lemma RETS : forall j i T, Rc i j T -->* Rc (i + j) 0 T.
Proof.
  induction j; intros i T.
  - rewrite Nat.add_0_r. apply evstep_refl.
  - eapply evstep_trans; [exact (RET i j T) |].
    replace (i + S j) with (S i + j) by lia. exact (IHj (S i) T).
Qed.

Lemma YCS : forall u i, Yc u i -->* Yc 0 (i + 2 * u).
Proof.
  induction u; intros i.
  - rewrite Nat.add_0_r. apply evstep_refl.
  - eapply evstep_trans; [exact (YC i u) |].
    replace (i + 2 * S u) with (S (S i) + 2 * u) by lia. exact (IHu (S (S i))).
Qed.

(** The common part of a borrow over k+2 zero digits: PRE, the walk, and (after the borrow lemma) the return. *)
Lemma R3_walk : forall a k P, 0 < a ->
  (grp a ([1;0;1]^^(S (S k)) *> 1 >> P)) {{G}}> const 0 -->* Wc a 0 (S k) P.
Proof.
  intros a k P Ha. unfold grp. rewrite zeros_snoc2.
  eapply evstep_trans; [exact (PRE a k P Ha) |].
  replace (S k) with (k + 1) by lia. exact (WALKS k a 1 P Ha).
Qed.

Lemma R3_ret : forall a k T,
  Rc 0 (S k) (0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> [0;1]^^a *> 1 >> T) -->*
  (grp 1 ([1;0;1]^^(S k) *> grp (S (S (S (S a)))) (1 >> T))) {{G}}> const 0.
Proof.
  intros a k T.
  eapply evstep_trans; [exact (RETS (S k) 0 _) |].
  unfold grp. rewrite zeros_snoc. exact (END a k T).
Qed.

(** ** The rules on the family (every one checked against the literal machine in verify_rules.py) *)

Lemma NR1 : forall a n l, N a 0 (S (S n)) l -->* N (S (S (S (S a)))) 0 n l.
Proof. intros. exact (R1 a n l). Qed.

Lemma NR23 : forall a k n l, 0 < a ->
  N a (S k) (S (S (S n))) (1 >> l) -->* N 1 k (S (S (S (S a)))) (grp (S n) (1 >> l)).
Proof.
  intros a k n l Ha. destruct k as [| k].
  - exact (R2 a n l Ha).
  - unfold N.
    eapply evstep_trans; [exact (R3_walk a k ([0;1]^^(S (S (S n))) *> 1 >> l) Ha) |].
    eapply evstep_trans; [exact (BOR a k n l Ha) |].
    exact (R3_ret a k (0 >> 1 >> [0;1]^^n *> 1 >> l)).
Qed.

Lemma NR23z : forall a k, 0 < a ->
  N a (S k) 2 (1 >> const 0) -->* N 1 k (S (S (S (S a)))) (grp 0 (1 >> const 0)).
Proof.
  intros a k Ha. destruct k as [| k].
  - exact (R2z a Ha).
  - unfold N.
    eapply evstep_trans; [exact (R3_walk a k (0 >> 1 >> 0 >> 1 >> 1 >> const 0) Ha) |].
    eapply evstep_trans; [exact (BORz a k Ha) |].
    exact (R3_ret a k (1 >> const 0)).
Qed.

(** The rebuild: all M >= 2 digits zero (the top digit is a zero digit too) -> top entry 6, 2a+M+4 zero digits. *)
Definition Ex (a M : nat) : Q * tape := (grp a ([1;0;1]^^M *> 1 >> const 0)) {{G}}> const 0.

Lemma REBUILD : forall a M, 0 < a -> Ex a (S (S M)) -->* N 1 (2 * a + M + 6) 6 (1 >> const 0).
Proof.
  intros a M Ha. unfold Ex.
  eapply evstep_trans; [exact (R3_walk a M (const 0) Ha) |].
  eapply evstep_trans; [exact (LASTW a (S M) Ha) |].
  eapply evstep_trans; [exact (YCS (S (S (S a))) (S (S M))) |].
  replace (S (S M) + 2 * S (S (S a))) with (S (2 * a + M + 7)) by lia.
  eapply evstep_trans; [exact (YEND (2 * a + M + 7)) |].
  replace (2 * a + M + 7) with (S (S (2 * a + M + 5))) by lia.
  rewrite zeros_snoc2.
  eapply evstep_trans; [exact (PRE 2 (2 * a + M + 5) (0 >> 1 >> 0 >> 1 >> const 0) ltac:(lia)) |].
  eapply evstep_trans; [exact (WALKS (2 * a + M + 5) 2 1 _ ltac:(lia)) |].
  replace (2 * a + M + 5 + 1) with (S (2 * a + M + 5)) by lia.
  eapply evstep_trans; [exact (BORn 2 (2 * a + M + 5) ltac:(lia)) |].
  replace (2 * a + M + 6) with (S (2 * a + M + 5)) by lia.
  exact (R3_ret 2 (2 * a + M + 5) (const 0)).
Qed.

(** The halt: top entry 0 (the word starts 11), L >= 2 zero digits.  cH is the halting configuration (state J
    reads a 0: J0 is undefined). *)
Definition cH (a i : nat) : Q * tape :=
  (const 0) <{{J}} (0 >> 1 >> 1 >> 1 >> [0;1]^^a *> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 0 >> [1;0;1]^^i *> const 0).

Lemma cH_halted : forall a i, halted tm (cH a i).
Proof. intros. unfold cH. simpl. reflexivity. Qed.

Lemma HALTN : forall a L, 0 < a -> N a (S (S L)) 0 (1 >> const 0) -->* cH a (S L).
Proof.
  intros a L Ha. unfold N.
  eapply evstep_trans; [exact (R3_walk a L (1 >> const 0) Ha) |].
  exact (HEND_st1 a (S L)).
Qed.

Lemma Neq : forall x j u l, N x j 1 (grp u l) = N x (S j) u l.
Proof. intros. unfold N, grp. rewrite (zeros_snoc j). reflexivity. Qed.

(** * Part 3: the abstract run *)

Fixpoint iter (n : nat) (g : nat -> nat) (x : nat) : nat :=
  match n with
  | O => x
  | S n' => g (iter n' g x)
  end.

Lemma iter_S' : forall n g x, iter (S n) g x = iter n g (g x).
Proof. induction n; intros; simpl. - reflexivity. - rewrite <- IHn. reflexivity. Qed.

(** F k b: the accumulator b' after clearing ONE unit of a digit at depth k (k zero digits between it and the
    accumulator), starting from accumulator b (accumulator b = 2b+1 units).  F 0 b = b + 2 (rule R1);
    F (k+1) b = (F k)^(b+2) (0) (rule R23 writes the digit b+2 at depth k and resets the accumulator to 0). *)
Fixpoint F (k : nat) : nat -> nat :=
  match k with
  | O => fun b => b + 2
  | S j => fun b => iter (b + 2) (F j) 0
  end.

Lemma F_S : forall j b, F (S j) b = iter (b + 2) (F j) 0.
Proof. reflexivity. Qed.

(** Clearing a digit with u units (2u+1 cells) at depth k. *)
Lemma CLR : forall k u b l, N (2 * b + 1) k (2 * u + 1) (1 >> l) -->* N (2 * iter u (F k) b + 1) k 1 (1 >> l).
Proof.
  induction k as [| j IHj]; intros u; induction u as [| u IHu]; intros b l.
  - apply evstep_refl.
  - replace (2 * S u + 1) with (S (S (2 * u + 1))) by lia.
    eapply evstep_trans; [exact (NR1 (2 * b + 1) (2 * u + 1) (1 >> l)) |].
    replace (S (S (S (S (2 * b + 1))))) with (2 * (b + 2) + 1) by lia.
    rewrite iter_S'. exact (IHu (b + 2) l).
  - apply evstep_refl.
  - replace (2 * S u + 1) with (S (S (S (2 * u)))) by lia.
    eapply evstep_trans; [exact (NR23 (2 * b + 1) j (2 * u) l ltac:(lia)) |].
    replace (S (S (S (S (2 * b + 1))))) with (2 * (b + 2) + 1) by lia.
    change (N 1 j (2 * (b + 2) + 1) (grp (S (2 * u)) (1 >> l)))
      with (N (2 * 0 + 1) j (2 * (b + 2) + 1) (1 >> [0;1]^^(S (2 * u)) *> 1 >> l)).
    eapply evstep_trans; [exact (IHj (b + 2) 0%nat ([0;1]^^(S (2 * u)) *> 1 >> l)) |].
    change (1 >> [0;1]^^(S (2 * u)) *> 1 >> l) with (grp (S (2 * u)) (1 >> l)).
    rewrite Neq. replace (S (2 * u)) with (2 * u + 1) by lia.
    rewrite iter_S'. change (iter (b + 2) (F j) 0) with (F (S j) b).
    exact (IHu (F (S j) b) l).
Qed.

(** Clearing the top entry of a rebuilt list: 2u cells, its zero is 0 cells (the word then starts 11). *)
Lemma CLRtop : forall k u b, N (2 * b + 1) (S k) (2 * u) (1 >> const 0) -->*
  N (2 * iter u (F (S k)) b + 1) (S k) 0 (1 >> const 0).
Proof.
  intros k u. induction u as [| u IHu]; intros b.
  - apply evstep_refl.
  - destruct u as [| u].
    + change (2 * 1) with 2.
      eapply evstep_trans; [exact (NR23z (2 * b + 1) k ltac:(lia)) |].
      replace (S (S (S (S (2 * b + 1))))) with (2 * (b + 2) + 1) by lia.
      change (N 1 k (2 * (b + 2) + 1) (grp 0 (1 >> const 0)))
        with (N (2 * 0 + 1) k (2 * (b + 2) + 1) (1 >> [0;1]^^0 *> 1 >> const 0)).
      eapply evstep_trans; [exact (CLR k (b + 2) 0%nat ([0;1]^^0 *> 1 >> const 0)) |].
      change (1 >> [0;1]^^0 *> 1 >> const 0) with (grp 0 (1 >> const 0)).
      rewrite Neq. apply evstep_refl.
    + replace (2 * S (S u)) with (S (S (S (2 * u + 1)))) by lia.
      eapply evstep_trans; [exact (NR23 (2 * b + 1) k (2 * u + 1) (const 0) ltac:(lia)) |].
      replace (S (S (S (S (2 * b + 1))))) with (2 * (b + 2) + 1) by lia.
      change (N 1 k (2 * (b + 2) + 1) (grp (S (2 * u + 1)) (1 >> const 0)))
        with (N (2 * 0 + 1) k (2 * (b + 2) + 1) (1 >> [0;1]^^(S (2 * u + 1)) *> 1 >> const 0)).
      eapply evstep_trans; [exact (CLR k (b + 2) 0%nat ([0;1]^^(S (2 * u + 1)) *> 1 >> const 0)) |].
      change (1 >> [0;1]^^(S (2 * u + 1)) *> 1 >> const 0) with (grp (S (2 * u + 1)) (1 >> const 0)).
      rewrite Neq. replace (S (2 * u + 1)) with (2 * S u) by lia.
      rewrite iter_S'. change (iter (b + 2) (F k) 0) with (F (S k) b).
      exact (IHu (F (S k) b)).
Qed.

(** ** The run from the blank tape *)

Lemma init_reach : c0 -->* N 1 26 5 (1 >> const 0).
Proof.
  unfold c0, N, grp.
  do 3890 step.
  apply evstep_refl'. reflexivity.
Qed.

(** b_f: the accumulator at the first exhaustion; b_2: the final accumulator.  Both are sealed (Qed'd sigma
    types) so that no tactic can ever try to compute them. *)
Lemma bf_sig : { x : nat | x = iter 2 (F 26) 0 }.
Proof. exists (iter 2 (F 26) 0). reflexivity. Qed.
Definition bf : nat := proj1_sig bf_sig.
Lemma bf_eq : bf = iter 2 (F 26) 0.
Proof. exact (proj2_sig bf_sig). Qed.

Lemma b2_sig : { x : nat | x = iter 3 (F (4 * bf + 33)) 0 }.
Proof. exists (iter 3 (F (4 * bf + 33)) 0). reflexivity. Qed.
Definition b2 : nat := proj1_sig b2_sig.
Lemma b2_eq : b2 = iter 3 (F (4 * bf + 33)) 0.
Proof. exact (proj2_sig b2_sig). Qed.

Lemma first_clear : N 1 26 5 (1 >> const 0) -->* Ex (2 * bf + 1) 27.
Proof.
  change (N 1 26 5 (1 >> const 0)) with (N (2 * 0 + 1) 26 (2 * 2 + 1) (1 >> const 0)).
  eapply evstep_trans; [exact (CLR 26 2 0 (const 0)) |].
  rewrite <- bf_eq. unfold N, Ex, grp. rewrite (zeros_snoc 26). apply evstep_refl.
Qed.

Lemma rebuild_run : Ex (2 * bf + 1) 27 -->* N 1 (4 * bf + 33) 6 (1 >> const 0).
Proof.
  replace (4 * bf + 33) with (2 * (2 * bf + 1) + 25 + 6) by lia.
  exact (REBUILD (2 * bf + 1) 25 ltac:(lia)).
Qed.

Lemma second_clear : N 1 (4 * bf + 33) 6 (1 >> const 0) -->* N (2 * b2 + 1) (4 * bf + 33) 0 (1 >> const 0).
Proof.
  rewrite b2_eq.
  replace (4 * bf + 33) with (S (4 * bf + 32)) by lia.
  change (N 1 (S (4 * bf + 32)) 6 (1 >> const 0)) with (N (2 * 0 + 1) (S (4 * bf + 32)) (2 * 3) (1 >> const 0)).
  exact (CLRtop (4 * bf + 32) 3 0).
Qed.

Theorem run_to_halt : c0 -->* cH (2 * b2 + 1) (4 * bf + 32).
Proof.
  eapply evstep_trans; [exact init_reach |].
  eapply evstep_trans; [exact first_clear |].
  eapply evstep_trans; [exact rebuild_run |].
  eapply evstep_trans; [exact second_clear |].
  replace (4 * bf + 33) with (S (S (4 * bf + 31))) by lia.
  replace (4 * bf + 32) with (S (4 * bf + 31)) by lia.
  exact (HALTN (2 * b2 + 1) (4 * bf + 31) ltac:(lia)).
Qed.

Theorem halt : halts tm c0.
Proof.
  destruct (with_counter run_to_halt) as [n Hn].
  eapply halts_multistep; [| exact Hn].
  apply halted_halts. apply cH_halted.
Qed.
