(** * A machine-checked score for the BB(10) champion *)

(** Machine (Racheline 2024, wiki "Champions" table, listed as sigma > f_omega^2(25) = f_omega(f_omega(25))):
      1RB1RA_0LC0LF_0RD1LC_1RA1RG_1RZ0RA_1LB1LF_1LH1RE_0LI1LH_0LF0LJ_1LH0LJ
    The machine table [tm], the digit family [Kd], the rules and the run are imported unchanged from
    BB10_champion_1RB1RA.v (which proves [halt : halts tm c0] and passes check.py).  Generated by
    bb8_list/investigations/bb10_champion_1RB1RA_0LF0LJ/coq/gen_bound.py; the fast-growing-hierarchy lemmas are those
    of BB9_champion_bound.v (same clearing functions U, X).

    Main results (no axioms):
      Theorem score_exact : exists c, c0 -->* c /\ halted tm c /\ ones c (b2 + 3).
      Theorem sigma_lower_bound :
        exists c N, c0 -->* c /\ halted tm c /\ ones c N /\ f_omega (f_omega 25) < N + 1.
      Theorem sigma_lower_bound_strong : exists c N b, c0 -->* c /\ halted tm c /\ ones c N /\
        2 ^ 25 * f 25 (f 25 2) <= b /\ b mod 8 = 0 /\ f_omega (3 * (b / 4) + 3) < N + 1.     (b = b1)

    Definitions as in BB9_champion_bound.v: f 0 n = n + 1, f (k+1) n = (f k)^n (n), f_omega n = f n n;
    [ones c N]: the tape of c holds exactly N ones.  busycoq stops before the halting transition E0 = 1RZ, which
    writes one more 1 (the head reads 0 in [c_end]), so the standard score is N + 1 = b2 + 4.

    Exact values:  b1 = Tv 7 1 7,  b2 = Tv (b1/4) 1 7,  Tv m j B = U (j+3m+2) (U (j+3m+2) (Tpre m j B)),
    Tpre clears the m (0,0,3) triples of trip m from depth j (digit 3 at depths j+2, j+5, ..., j+3m-1). *)

From BB8 Require Import Individual102.
From BB8 Require Import BB10_champion_1RB1RA.
From Coq Require Import Lia PeanoNat List Wf_nat.
Import ListNotations.
Set Default Goal Selector "!".

(** The imported [tm] is the declared machine (BB10_champion_1RB1RA.v passes check.py, which checks this). *)
(* machine: 1RB1RA_0LC0LF_0RD1LC_1RA1RG_1RZ0RA_1LB1LF_1LH1RE_0LI1LH_0LF0LJ_1LH0LJ *)
Lemma tm_table :
  tm (A, 0) = Some (1, R, B) /\ tm (A, 1) = Some (1, R, A) /\
  tm (B, 0) = Some (0, L, C) /\ tm (B, 1) = Some (0, L, F) /\
  tm (C, 0) = Some (0, R, D) /\ tm (C, 1) = Some (1, L, C) /\
  tm (D, 0) = Some (1, R, A) /\ tm (D, 1) = Some (1, R, G) /\
  tm (E, 0) = None           /\ tm (E, 1) = Some (0, R, A) /\
  tm (F, 0) = Some (1, L, B) /\ tm (F, 1) = Some (1, L, F) /\
  tm (G, 0) = Some (1, L, H) /\ tm (G, 1) = Some (1, R, E) /\
  tm (H, 0) = Some (0, L, I) /\ tm (H, 1) = Some (1, L, H) /\
  tm (I, 0) = Some (0, L, F) /\ tm (I, 1) = Some (0, L, J) /\
  tm (J, 0) = Some (1, L, H) /\ tm (J, 1) = Some (0, L, J).
Proof. repeat split. Qed.

Local Open Scope nat_scope.

(** Never let a tactic compute these numbers (Opaque declarations are not exported by the imported file). *)
Opaque U X Tv b1 b2.

(** ** Definitions used in the statement *)

(** The fast-growing hierarchy: f 0 n = n + 1, f (k+1) n = (f k)^n (n), f_omega n = f n n.
    ([iter n g x] = g^n(x) is defined in BB10_champion_1RB1RA.v: iter 0 g x = x, iter (S n) g x = g (iter n g x).) *)
Fixpoint f (k : nat) : nat -> nat :=
  match k with
  | O => S
  | S k' => fun n => iter n (f k') n
  end.

Definition f_omega (n : nat) : nat := f n n.

Definition sym_val (s : Sym) : nat :=
  match s with
  | S0 => 0
  | S1 => 1
  end.

Fixpoint count1 (xs : list Sym) : nat :=
  match xs with
  | [] => 0
  | x :: t => sym_val x + count1 t
  end.

(** [ones c N]: the tape of c is  L (reversed, left of the head), s (head cell), R (right of the head),
    with 0s beyond both lists, and N = number of 1s in L, s, R. *)
Definition ones (c : state * tape) (N : nat) : Prop :=
  exists (q : state) (L R : list Sym) (s : Sym),
    c = (q, (L *> const S0, s, R *> const S0)) /\ N = count1 L + sym_val s + count1 R.

Lemma count1_blocks : forall m, count1 ([S0; S1; S1]^^m) = 2 * m.
Proof. induction m. - reflexivity. - simpl. rewrite IHm. lia. Qed.

Lemma ones_c_end : forall m, ones (c_end m) (2 * m + 4).
Proof.
  intros m. exists E, ([S1; S1; S0; S1; S1] ++ [S0; S1; S1]^^m), (@nil Sym), S0. split.
  - reflexivity.
  - simpl. rewrite count1_blocks. lia.
Qed.

(** Domination of iterates through the scaling z >= K n. *)
Lemma iter_dom : forall K g h, (forall n z, K * n <= z -> K * g n <= h z) ->
  forall m n z, K * n <= z -> K * iter m g n <= iter m h z.
Proof. intros K g h Hd. induction m; intros n z Hz; simpl; auto. Qed.

(** ** The fast-growing hierarchy: basic facts *)

Lemma f_S : forall k n, f (S k) n = iter n (f k) n.
Proof. reflexivity. Qed.

Lemma f_props : forall k, (forall n, n <= f k n) /\ (forall a b, a <= b -> f k a <= f k b).
Proof.
  induction k as [| k [Hid Hmono]].
  - split; intros; simpl; lia.
  - split.
    + intros n. rewrite f_S. apply iter_ge. exact Hid.
    + intros a b Hab. rewrite !f_S. transitivity (iter a (f k) b).
      * apply iter_mono_x; assumption.
      * apply iter_mono_n; assumption.
Qed.

Lemma f_id : forall k n, n <= f k n.
Proof. intros. apply f_props. Qed.

Lemma f_mono : forall k a b, a <= b -> f k a <= f k b.
Proof. intros. apply f_props. assumption. Qed.

Lemma f_gt : forall k n, 1 <= n -> n < f k n.
Proof.
  induction k; intros n Hn.
  - simpl. lia.
  - rewrite f_S. destruct n as [| n']; [lia |].
    simpl. pose proof (iter_ge (f k) (f_id k) n' (S n')).
    specialize (IHk (iter n' (f k) (S n')) ltac:(lia)). lia.
Qed.

Lemma f_level : forall k n, 1 <= n -> f k n <= f (S k) n.
Proof.
  intros k n Hn. rewrite f_S. destruct n as [| n']; [lia |].
  rewrite iter_S'. apply iter_ge. apply f_id.
Qed.

Lemma f_level_mono : forall d k n, 1 <= n -> f k n <= f (d + k) n.
Proof.
  induction d; intros k n Hn. - reflexivity.
  - specialize (IHd k n Hn). pose proof (f_level (d + k) n Hn). change (S d + k) with (S (d + k)). lia.
Qed.

Lemma iter_succ_add : forall n x, iter n S x = n + x.
Proof. induction n; intros; simpl. - reflexivity. - rewrite IHn. reflexivity. Qed.

Lemma f1 : forall n, f 1 n = 2 * n.
Proof. intros. rewrite f_S. rewrite iter_succ_add. lia. Qed.

Lemma f_dbl : forall k n, 1 <= k -> 2 * n <= f k n.
Proof.
  intros k n Hk. destruct n as [| n']. - lia.
  - rewrite <- f1. replace k with ((k - 1) + 1) by lia. apply f_level_mono. lia.
Qed.

(** ** The lower bound for U: level j+1 of the fast-growing hierarchy, with scaling 2^(j+1) *)

Lemma pow2_ge : forall j, j + 2 <= 2 ^ (j + 1).
Proof. induction j. - simpl. lia. - change (S j + 1) with (S (j + 1)). rewrite Nat.pow_succ_r'. lia. Qed.

Lemma bound : forall j,
  (forall n z, 2 ^ (j + 1) * n <= z -> 2 ^ (j + 1) * f (S j) n <= U j z) /\
  2 ^ (j + 2) * (j + 1) <= X j.
Proof.
  induction j as [| j [Hu Hx]].
  - split.
    + intros n z Hz. rewrite U_0, f1. simpl (2 ^ (0 + 1)) in *. lia.
    + rewrite X_0. simpl. lia.
  - pose proof (pow2_ge j) as HKj.
    set (K := 2 ^ (j + 1)) in *.
    assert (HK1 : 2 ^ (S j + 1) = 2 * K) by (unfold K; rewrite !Nat.pow_add_r; simpl; lia).
    assert (HK2 : 2 ^ (j + 2) = 2 * K) by (unfold K; rewrite !Nat.pow_add_r; simpl; lia).
    assert (HK3 : 2 ^ (S j + 2) = 4 * K) by (unfold K; rewrite !Nat.pow_add_r; simpl; lia).
    rewrite HK2 in Hx.
    assert (HX1 : K * 1 <= X j) by nia.
    split.
    + intros n y Hy. rewrite HK1 in *. rewrite U_S, f_S.
      destruct n as [| n']. { simpl. lia. }
      set (n := S n') in *.
      assert (Hm : 2 * n + 1 <= y - 2 * j) by nia.
      pose proof (iter_dom K (f (S j)) (U j) Hu (y - 2 * j) 1 (X j) HX1) as Hd.
      assert (Hc : 2 * iter n (f (S j)) n <= iter (y - 2 * j) (f (S j)) 1).
      { transitivity (iter (2 * n + 1) (f (S j)) 1).
        2:{ apply iter_mono_n; [apply f_id | exact Hm]. }
        replace (2 * n + 1) with (1 + (n + n)) by lia. rewrite !iter_add.
        change (iter 1 (f (S j)) ?z) with (f (S j) z).
        pose proof (iter_lin1 (f (S j)) ltac:(intros a Ha; pose proof (f_gt (S j) a Ha); lia) n 1 ltac:(lia)).
        pose proof (iter_mono_x (f (S j)) (f_mono (S j)) n n (iter n (f (S j)) 1) ltac:(lia)).
        pose proof (f_dbl (S j) (iter n (f (S j)) (iter n (f (S j)) 1)) ltac:(lia)).
        lia. }
      nia.
    + rewrite HK3, X_S.
      pose proof (Hu (2 * (j + 1)) (X j) ltac:(nia)) as H1.
      pose proof (f_dbl (S j) (2 * (j + 1)) ltac:(lia)) as H2.
      pose proof (Hu (4 * (j + 1)) (U j (X j)) ltac:(nia)) as H3.
      pose proof (f_dbl (S j) (4 * (j + 1)) ltac:(lia)) as H4.
      nia.
Qed.

Lemma Ubound : forall j n z, 2 ^ (j + 1) * n <= z -> 2 ^ (j + 1) * f (S j) n <= U j z.
Proof. intro j. apply (proj1 (bound j)). Qed.

Lemma Xbound : forall j, 2 ^ (j + 2) * (j + 1) <= X j.
Proof. intro j. apply (proj2 (bound j)). Qed.


(** ** The run's two clearings, from below *)

Lemma Tpre_last : forall m j B, Tpre (S m) j B = iter 3 (U (j + 3 * m + 2)) (Tpre m j B).
Proof.
  induction m; intros j B.
  - cbn [Tpre]. replace (j + 3 * 0 + 2) with (j + 2) by lia. reflexivity.
  - change (Tpre (S (S m)) j B) with (Tpre (S m) (j + 3) (iter 3 (U (j + 2)) B)).
    rewrite IHm. cbn [Tpre]. replace (j + 3 + 3 * m + 2) with (j + 3 * S m + 2) by lia. reflexivity.
Qed.

Lemma Tv_unfold : forall m j B, Tv m j B = U (j + 3 * m + 2) (U (j + 3 * m + 2) (Tpre m j B)).
Proof. Transparent Tv. reflexivity. Qed.
Opaque Tv.

Lemma f3_2 : f 3 2 = 2048.
Proof. reflexivity. Qed.

Opaque f.

(** b1 >= 2^25 * f_25(f_25(2)) *)
Lemma b1_big : 2 ^ 25 * f 25 (f 25 2) <= b1.
Proof.
  rewrite b1_def, Tv_unfold. change (1 + 3 * 7 + 2) with 24.
  rewrite (Tpre_last 6 1 7). change (1 + 3 * 6 + 2) with 21.
  set (T6 := Tpre 6 1 7). cbn [iter].
  pose proof (U_ge_X 20 (U 21 (U 21 T6))) as Hz. change (S 20) with 21 in Hz.
  pose proof (Xbound 20) as HX. change (2 ^ (20 + 2)) with (2 ^ 22) in HX.
  assert (Hn : 2 ^ (21 + 1) * 21 <= U 21 (U 21 T6)).
  { change (2 ^ (21 + 1)) with (2 ^ 22). pose proof (U_ge_X 20 (U 21 T6)) as Hz'. change (S 20) with 21 in Hz'. nia. }
  pose proof (Ubound 21 21 _ Hn) as H7. change (S 21) with 22 in H7. change (2 ^ (21 + 1)) with (2 ^ 22) in H7.
  pose proof (f_dbl 22 21 ltac:(lia)) as Hd.
  assert (H2 : 2 ^ (24 + 1) * 2 <= U 21 (U 21 (U 21 T6))).
  { replace (24 + 1) with (22 + 3) by lia. rewrite Nat.pow_add_r. change (2 ^ 3) with 8.
    set (P := 2 ^ 22) in *. set (Z := U 21 (U 21 (U 21 T6))) in *. nia. }
  pose proof (Ubound 24 2 _ H2) as H8. change (S 24) with 25 in H8.
  pose proof (Ubound 24 (f 25 2) _ H8) as H9. change (S 24) with 25 in H9. change (2 ^ (24 + 1)) with (2 ^ 25) in H9.
  exact H9.
Qed.

Lemma f25_2 : 25 <= f 25 2.
Proof.
  pose proof (f_level_mono 22 3 2 ltac:(lia)) as H. change (22 + 3) with 25 in H. rewrite f3_2 in H. lia.
Qed.

Lemma quarter_aux : forall b y z P, P * y <= b -> z <= y -> 4 <= P -> z <= b / 4.
Proof. intros b y z P H1 H2 H3. apply Nat.div_le_lower_bound; [lia | nia]. Qed.

Lemma b1_quarter : f 25 25 <= b1 / 4.
Proof.
  assert (Hp : 2 ^ 2 <= 2 ^ 25) by (apply Nat.pow_le_mono_r; lia). change (2 ^ 2) with 4 in Hp.
  exact (quarter_aux b1 _ _ _ b1_big (f_mono 25 25 (f 25 2) f25_2) Hp).
Qed.

(** b2 = Tv m 1 7 >= f_omega (3m + 3): the deepest digit of the second list sits at depth 3m + 3 *)
Lemma second_big : forall m, f_omega (3 * m + 3) <= Tv m 1 7.
Proof.
  intros m. rewrite Tv_unfold. replace (1 + 3 * m + 2) with (S (3 * m + 2)) by lia.
  set (J := S (3 * m + 2)). set (w := Tpre m 1 7).
  pose proof (U_ge_X (3 * m + 2) w) as Hw. fold J in Hw.
  pose proof (Xbound (3 * m + 2)) as HX.
  replace (3 * m + 2 + 2) with (J + 1) in HX by (unfold J; lia).
  replace (3 * m + 2 + 1) with J in HX by (unfold J; lia).
  assert (Hn : 2 ^ (J + 1) * J <= U J w) by lia.
  pose proof (Ubound J J _ Hn) as Hb.
  assert (L1 : f J J <= f (S J) J) by (apply f_level; unfold J; lia).
  assert (L2 : 1 <= 2 ^ (J + 1)) by (apply Nat.neq_0_lt_0, Nat.pow_nonzero; lia).
  unfold f_omega. replace (3 * m + 3) with J by (unfold J; lia).
  set (P := 2 ^ (J + 1)) in *. set (y := f (S J) J) in *. set (Z := U J (U J w)) in *. nia.
Qed.

Lemma f_omega_mono : forall a b, 1 <= a -> a <= b -> f_omega a <= f_omega b.
Proof.
  intros a b Ha Hab. unfold f_omega.
  pose proof (f_level_mono (b - a) a a Ha) as L1. replace (b - a + a) with b in L1 by lia.
  pose proof (f_mono b a b Hab). lia.
Qed.

(** ** Main theorems *)

Lemma ones_odd : forall b, b mod 2 = 1 -> ones (c_end (b / 2)) (b + 3).
Proof.
  intros b Hb. pose proof (odd_half b Hb) as Hb'.
  replace (b + 3) with (2 * (b / 2) + 4) by lia. apply ones_c_end.
Qed.

Theorem score_exact : exists c, c0 -->* c /\ halted tm c /\ ones c (b2 + 3).
Proof.
  exists (c_end (b2 / 2)). split; [exact run2 |]. split; [apply c_end_halted |].
  apply ones_odd, b2_odd.
Qed.

Lemma b2_big : f_omega (3 * (b1 / 4) + 3) <= b2.
Proof. rewrite b2_def. unfold second. apply second_big. Qed.

Theorem sigma_lower_bound_strong : exists c N b, c0 -->* c /\ halted tm c /\ ones c N /\
  2 ^ 25 * f 25 (f 25 2) <= b /\ b mod 8 = 0 /\ f_omega (3 * (b / 4) + 3) < N + 1.
Proof.
  destruct score_exact as [c [H1 [H2 H3]]].
  exists c, (b2 + 3), b1.
  (* explicit splits: [repeat split] would try eq_refl on [b1 mod 8 = 0] and evaluate b1 *)
  split; [exact H1 |]. split; [exact H2 |]. split; [exact H3 |].
  split; [exact b1_big |]. split; [exact b1_mod8 |].
  pose proof b2_big as Hb. set (t := f_omega (3 * (b1 / 4) + 3)) in *. lia.
Qed.

Lemma final_arith : forall q v, f 25 25 <= q -> f_omega (3 * q + 3) <= v -> f_omega (f_omega 25) < v + 3 + 1.
Proof.
  intros q v Hq Hv.
  assert (Hpos : 1 <= f_omega 25) by (unfold f_omega; pose proof (f_id 25 25); lia).
  assert (Hle : f_omega 25 <= 3 * q + 3) by (unfold f_omega; lia).
  pose proof (f_omega_mono _ _ Hpos Hle). lia.
Qed.

Theorem sigma_lower_bound : exists c N, c0 -->* c /\ halted tm c /\ ones c N /\ f_omega (f_omega 25) < N + 1.
Proof.
  destruct score_exact as [c [H1 [H2 H3]]].
  exists c, (b2 + 3).
  split; [exact H1 |]. split; [exact H2 |]. split; [exact H3 |].
  exact (final_arith (b1 / 4) b2 b1_quarter b2_big).
Qed.

Print Assumptions score_exact.
Print Assumptions sigma_lower_bound.
Print Assumptions sigma_lower_bound_strong.
