(** * Score of the BB(10) candidate n1 = 1RB0RA_1LC1LF_1RD0LB_1RA1LE_1LI0LC_0RG1LD_1RH1LG_1LC0RG_0LJ0LI_---0LC *)

(** Generated by bb8_list/investigations/bb10_n1_coq (gen_bound.py from bound.v.in).
    Imports the halting proof BB10_n1.v unchanged (tm, c0, the run, the generated lemmas).

    Convention: busycoq stops BEFORE the undefined transition; the halting configuration [c_halt] is in state J
    reading a 0 (J0 undefined), and [ones c N] counts the ones on that tape.  The standard score (the halting
    transition treated as 1RZ, writing a 1 on the 0) is N + 1.

    Notation: T = 2 ^(37 arrows) 3 (= 2 B + 4 for the BB(8) record's final accumulator B), F n = 2 ^(n arrows) 4
    = 2 ^(n+1 arrows) 3, JJ = (3 T - 13) / 7 (the number of full periods).

    Main results (no axioms):
      score_exact       : the halt has 2 w + f + 3 k + 22 ones, for the explicit final w, f, k of the run,
                          with w >= F^(2 JJ + 1) (34);
      sigma_lower_bound : ones > G^((6 T - 19) / 7) (33), G x = 2 ^(x+1 arrows) 3   (the verifier's G^N(33),
                          N = (12 B + 5) / 7 growth events);
      dominates         : ones > (2 ^(K arrows))^x (x) for all K, x <= F (F (F 34))
                          (F (F (F 34)) is far beyond 4 T + 41, the index of M3's proved lower bound);
      beats_M3_bound    : ones > M3's proved lower bound arrow (4T+41) 2 (arrow (4T+39) 2 (arrow (4T+35) 2 5));
      beats_lead        : the 10-state candidate 0LJ0LC (BB10_lead_bound.score_exact) halts with Nl ones and
                          Nl + 1 < N + 1;
      beats_champion    : the BB(10) champion (BB10_champion_bound.score_exact) halts with Nc ones and
                          Nc + 1 < N + 1 (via BB10_lead_vs_champion.b2c_le).
      arrow_agree       : [arrow] here coincides with BB10_lead_bound.arrow. *)

From BB8 Require Import Individual102.
From BB8 Require Import BB10_n1.
From BB8 Require BB10_lead_1RB0RA BB10_lead_bound BB10_lead_vs_champion BB10_champion_1RB1RA BB10_champion_bound.
From Coq Require Import Lia PeanoNat List.
Import ListNotations.
Set Default Goal Selector "!".

Local Open Scope nat_scope.

(** [arrow] of BB10_lead_bound.v is the same Fixpoint as ours (separately defined: needs a proof). *)
Lemma arrow_agree : forall k a b, BB10_lead_bound.arrow k a b = arrow k a b.
Proof.
  induction k as [| k IH]; intros a b; [reflexivity |].
  simpl. induction b as [| b IHb]; [reflexivity |]. simpl. rewrite IHb, IH. reflexivity.
Qed.

Lemma F_def : forall n, F n = arrow n 2 4.
Proof. reflexivity. Qed.

(** Never let a tactic compute these numbers (Opaque declarations are not exported by the imported file). *)
Opaque U arrow F.

(** ** The halting configuration (the end of the generated lemma EV_HALT) *)

Definition c_halt (f k w : nat) : Q * tape :=
  (0 >> 0 >> 0 >> 0 >> 1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 1 >> 0 >> 1 >> [1;0;1;0;1]^^k *> const 0)%sym <{{J}} (0 >> 0 >> 1 >> 1 >> 1 >> 1 >> 0 >> 0 >> 1 >> 0 >> 0 >> 1 >> 0 >> 0 >> 1 >> 0 >> 0 >> 1 >> 0 >> 1 >> 0 >> 1 >> 0 >> [1;0]^^f *> 0 >> 1 >> 0 >> 1 >> [1;0;1]^^w *> const 0)%sym.

Lemma c_halt_halted : forall f k w, halted tm (c_halt f k w).
Proof. intros. reflexivity. Qed.

(** HALT_B of the halting file, with the halting configuration made explicit (same proof). *)
Lemma HALT_exact : forall k w f, Bf (FarE k) (repeat 1 w ++ [0]) f -->* c_halt f k w.
Proof. intros. unfold FarE. bnorm. follow (EV_HALT f k w). unfold c_halt. finish_norm. Qed.

Lemma reach_halt : exists k w f, c0 -->* c_halt f k w /\ iter (2 * JJ + 1) F 34 <= w.
Proof.
  destruct reach_end as [k [w [f [H1 H2]]]].
  exists k, w, f. split; [| exact H2]. follow H1. apply HALT_exact.
Qed.

(** ** Counting ones (the definitions of BB8_champ35_bound.v) *)

Definition sym_val (s : Sym) : nat :=
  match s with
  | S0 => 0
  | S1 => 1
  end.

Fixpoint count1 (xs : list Sym) : nat :=
  match xs with
  | [] => 0
  | x :: t => sym_val x + count1 t
  end.

(** [ones c N]: the tape of c is  L (reversed, left of the head), s (head cell), R (right of the head),
    with 0s beyond both lists, and N = number of 1s in L, s, R. *)
Definition ones (c : Q * tape) (N : nat) : Prop :=
  exists (q : Q) (L R : list Sym) (s : Sym),
    c = (q, (L *> const S0, s, R *> const S0)) /\ N = count1 L + sym_val s + count1 R.

Lemma count1_app : forall xs ys, count1 (xs ++ ys) = count1 xs + count1 ys.
Proof. induction xs; intros; simpl. - reflexivity. - rewrite IHxs. lia. Qed.

Lemma count1_pow : forall xs n, count1 (xs ^^ n) = n * count1 xs.
Proof. induction n; simpl. - reflexivity. - rewrite count1_app, IHn. lia. Qed.

Lemma ones_c_halt : forall f k w, ones (c_halt f k w) (2 * w + f + 3 * k + 22).
Proof.
  intros. exists J, ([S0;S0;S0;S1;S0;S0;S1;S0;S1;S0;S1;S0;S1;S0;S1;S0;S1;S0;S1;S1;S0;S1] ++ [S1;S0;S1;S0;S1]^^k), ([S0;S0;S1;S1;S1;S1;S0;S0;S1;S0;S0;S1;S0;S0;S1;S0;S0;S1;S0;S1;S0;S1;S0] ++ [S1;S0]^^f ++ [S0;S1;S0;S1] ++ [S1;S0;S1]^^w), S0.
  split.
  - unfold c_halt. rewrite !Str_app_assoc. reflexivity.
  - rewrite !count1_app, !count1_pow. simpl. lia.
Qed.

(** ** The score *)

Theorem score_exact : exists c f k w, c0 -->* c /\ halted tm c /\ ones c (2 * w + f + 3 * k + 22) /\
  iter (2 * JJ + 1) F 34 <= w.
Proof.
  destruct reach_halt as [k [w [f [H1 H2]]]].
  exists (c_halt f k w), f, k, w.
  split; [exact H1 | split; [apply c_halt_halted | split; [apply ones_c_halt | exact H2]]].
Qed.

Lemma score_ge : exists c N, c0 -->* c /\ halted tm c /\ ones c N /\ iter (2 * JJ + 1) F 34 < N.
Proof.
  destruct score_exact as [c [f [k [w [H1 [H2 [H3 H4]]]]]]].
  exists c, (2 * w + f + 3 * k + 22). split; [exact H1 | split; [exact H2 | split; [exact H3 |]]].
  revert H4. generalize (iter (2 * JJ + 1) F 34). intros. lia.
Qed.

(** ** Arithmetic on arrows *)

Lemma arrow_S_ge : forall k y, y + 1 <= arrow (S k) 2 y.
Proof. intros k [| y]; [rewrite arrow_S0; lia | apply arrow_gt; lia]. Qed.

Lemma arrow_double : forall k y, 2 * y <= arrow k 2 y.
Proof.
  induction k as [| k IH]; intros y.
  - rewrite (arrow_0 2 y). lia.
  - destruct y as [| y]; [rewrite arrow_S0; lia |].
    rewrite arrow_SS. pose proof (IH (arrow (S k) 2 y)). pose proof (arrow_S_ge k y). lia.
Qed.

Lemma arrow_lvl : forall k x, 2 <= x -> arrow k 2 x <= arrow (S k) 2 x.
Proof.
  intros k x Hx. induction x as [| x IH]; [lia |].
  destruct (Nat.eq_dec x 1) as [-> | Hx1].
  - rewrite (arrow_two k), (arrow_two (S k)). lia.
  - rewrite arrow_SS. specialize (IH ltac:(lia)).
    pose proof (arrow_gt k x ltac:(lia)).
    pose proof (arrow_mono k (S x) (arrow k 2 x) ltac:(lia)).
    pose proof (arrow_mono k (arrow k 2 x) (arrow (S k) 2 x) IH). lia.
Qed.

Lemma arrow_lvl_le : forall k K x, k <= K -> 2 <= x -> arrow k 2 x <= arrow K 2 x.
Proof.
  intros k K x HkK Hx. induction HkK; [lia |].
  pose proof (arrow_lvl m x Hx). lia.
Qed.

Lemma arrow_step2 : forall j x, 2 * arrow (S j) 2 x <= arrow (S j) 2 (S x).
Proof. intros. rewrite arrow_SS. apply arrow_double. Qed.

Lemma F_double : forall n, 2 * F n <= F (S n).
Proof. intros. rewrite F_S. apply arrow_double. Qed.

Lemma F34_big : 4 * F 26 + 19 <= F 34.
Proof.
  pose proof (F_double 26). pose proof (F_double 27). pose proof (F_double 28).
  pose proof (F_mono 29 34 ltac:(lia)). pose proof (F_ge 26).
  revert H H0 H1 H2 H3. generalize (F 26) (F 27) (F 28) (F 29) (F 34). intros. lia.
Qed.

(** iter 3 F 34 = F (F (F 34)) *)
Lemma iter3F : iter 3 F 34 = F (F (F 34)).
Proof. reflexivity. Qed.

Lemma JJ_ge2 : 2 <= JJ.
Proof.
  pose proof JJ_eq as [HJ _]. pose proof T_ge. revert HJ H. generalize T JJ. intros. lia.
Qed.

Lemma iter_big : forall j, 3 <= j -> F (F (F 34)) <= iter j F 34.
Proof.
  intros j Hj. replace j with ((j - 3) + 3) by lia. rewrite iter_add.
  rewrite iter3F. apply iterF_ge.
Qed.

(** ** The verifier's form: sigma > G^N(33), G x = 2 ^(x+1 arrows) 3, N = (12 B + 5) / 7 = (6 T - 19) / 7 *)

Lemma iter_G : forall n x, iter n (fun y => arrow (y + 1) 2 3) x = iter n F x.
Proof.
  induction n; intros; simpl; [reflexivity |].
  rewrite IHn, Nat.add_1_r, arrow_S3. reflexivity.
Qed.

Lemma N_eq : (6 * arrow 37 2 3 - 19) / 7 = 2 * JJ + 1.
Proof.
  rewrite <- T_def. destruct JJ_eq as [HJ _]. rewrite HJ.
  symmetry. apply Nat.div_unique with (r := 0); lia.
Qed.

Theorem sigma_lower_bound : exists c N, c0 -->* c /\ halted tm c /\ ones c N /\
  iter ((6 * arrow 37 2 3 - 19) / 7) (fun x => arrow (x + 1) 2 3) 33 < N.
Proof.
  destruct score_ge as [c [N [H1 [H2 [H3 H4]]]]].
  exists c, N. split; [exact H1 | split; [exact H2 | split; [exact H3 |]]].
  rewrite N_eq, iter_G. pose proof (iterF_mono (2 * JJ + 1) 33 34 ltac:(lia)). lia.
Qed.

(** ** Domination of every arrow-iterate with index and count up to F (F (F 34)) *)

Lemma arrow_add : forall K a b, arrow (S K) 2 (a + b) = iter a (arrow K 2) (arrow (S K) 2 b).
Proof. induction a; intros; simpl; [reflexivity |]. rewrite arrow_SS, IHa. reflexivity. Qed.

Lemma iter_arrow_le : forall K x, iter x (arrow K 2) x <= arrow (S K) 2 (2 * x).
Proof.
  intros. replace (2 * x) with (x + x) by lia. rewrite arrow_add.
  pose proof (arrow_S_ge K x).
  assert (Hm : forall n a b, a <= b -> iter n (arrow K 2) a <= iter n (arrow K 2) b).
  { induction n; intros; simpl; [lia | apply arrow_mono, IHn; lia]. }
  apply Hm. lia.
Qed.

Lemma F_lin : forall n, 4 <= n -> 8 * n + 48 <= F n.
Proof.
  intros n Hn. induction Hn.
  - pose proof (F_double 0). pose proof (F_double 1). pose proof (F_double 2). pose proof (F_double 3).
    rewrite F_0 in *. lia.
  - pose proof (F_double m). lia.
Qed.

Theorem dominates : exists c N, c0 -->* c /\ halted tm c /\ ones c N /\
  forall K x, K <= F (F (F 34)) -> x <= F (F (F 34)) -> iter x (arrow K 2) x < N.
Proof.
  destruct score_ge as [c [N [H1 [H2 [H3 H4]]]]].
  exists c, N. split; [exact H1 | split; [exact H2 | split; [exact H3 |]]].
  intros K x HK Hx.
  pose proof JJ_ge2 as HJ.
  assert (H5 : F (F (F (F (F 34)))) <= iter (2 * JJ + 1) F 34).
  { replace (2 * JJ + 1) with ((2 * JJ - 4) + 5) by lia. rewrite iter_add.
    change (iter 5 F 34) with (F (F (F (F (F 34))))). apply iterF_ge. }
  revert HK Hx H4 H5. generalize (F (F (F 34))). intros M HK Hx H4 H5.
  destruct x as [| x']; [simpl iter; lia |].
  (* F (F M) >= arrow (M + 2) 2 4 = arrow (M + 1) 2 (F (M + 1)) >= arrow (M + 1) 2 (2 x) >= arrow (S K) 2 (2 x) *)
  pose proof (F_ge M) as HFM.
  assert (A1 : arrow (M + 2) 2 4 <= F (F M)).
  { rewrite (F_def (F M)). apply arrow_lvl_le; lia. }
  assert (A2 : arrow (M + 2) 2 4 = arrow (M + 1) 2 (F (M + 1))).
  { replace (M + 2) with (S (M + 1)) by lia. replace 4 with (S 3) by reflexivity. rewrite arrow_SS, arrow_S3. reflexivity. }
  pose proof (F_double M) as HD. replace (S M) with (M + 1) in HD by lia.
  pose proof (arrow_mono (M + 1) (2 * S x') (F (M + 1)) ltac:(lia)) as A3.
  pose proof (arrow_lvl_le (S K) (M + 1) (2 * S x') ltac:(lia) ltac:(lia)) as A4.
  pose proof (iter_arrow_le K (S x')) as A5.
  lia.
Qed.

(** M3's proved lower bound (BB10_fw1_bound.sigma_lower_bound), as a closed expression *)
Theorem beats_M3_bound : exists c N, c0 -->* c /\ halted tm c /\ ones c N /\
  arrow (4 * arrow 37 2 3 + 41) 2 (arrow (4 * arrow 37 2 3 + 39) 2 (arrow (4 * arrow 37 2 3 + 35) 2 5)) < N.
Proof.
  destruct dominates as [c [N [H1 [H2 [H3 H4]]]]].
  exists c, N. split; [exact H1 | split; [exact H2 | split; [exact H3 |]]].
  rewrite <- T_def.
  assert (HM : 4 * T + 41 <= F (F (F 34))).
  { rewrite T_def, arrow_S3.
    pose proof (F_ge 34). pose proof (F_mono 36 (F 34) ltac:(lia)) as E1.
    pose proof (F_ge (F 34)). pose proof (F_lin (F (F 34)) ltac:(lia)) as E2.
    revert E1 E2. generalize (F 36) (F (F 34)) (F (F (F 34))). intros. lia. }
  specialize (H4 (4 * T + 41) 5 HM ltac:(pose proof (F_ge (F (F 34))); lia)).
  revert H4. generalize T. intros t H4.
  set (K := 4 * t + 41) in *.
  assert (P5 : 2 <= arrow K 2 5) by (pose proof (arrow_gt K 5 ltac:(lia)); lia).
  assert (L1 : arrow (4 * t + 35) 2 5 <= arrow K 2 5) by (apply arrow_lvl_le; unfold K; lia).
  assert (L2 : arrow (4 * t + 39) 2 (arrow (4 * t + 35) 2 5) <= arrow K 2 (arrow K 2 5)).
  { apply (Nat.le_trans _ (arrow (4 * t + 39) 2 (arrow K 2 5))); [apply arrow_mono; exact L1 |].
    apply arrow_lvl_le; [unfold K; lia | exact P5]. }
  assert (L3 : arrow K 2 (arrow (4 * t + 39) 2 (arrow (4 * t + 35) 2 5)) <= iter 3 (arrow K 2) 5).
  { change (iter 3 (arrow K 2) 5) with (arrow K 2 (arrow K 2 (arrow K 2 5))). apply arrow_mono. exact L2. }
  assert (L4 : iter 3 (arrow K 2) 5 <= iter 5 (arrow K 2) 5).
  { apply iter_mono_n; [intros; apply arrow_props | lia]. }
  unfold K in *. lia.
Qed.

(** ** The 10-state candidate 0LJ0LC and the BB(10) champion *)

(** a count 2 (Y - 4) + 2 L + 5 with Y = 2 ^(L arrows) 5 is below 2 ^(L+2 arrows) 4 *)
Lemma lead_count_lt : forall L, 1 <= L -> 2 * (arrow L 2 5 - 4) + 2 * L + 5 < arrow (L + 2) 2 4.
Proof.
  intros L HL.
  assert (E1 : arrow (L + 2) 2 4 = arrow (L + 1) 2 (F (L + 1))).
  { replace (L + 2) with (S (L + 1)) by lia. replace 4 with (S 3) by reflexivity. rewrite arrow_SS, arrow_S3. reflexivity. }
  pose proof (F_ge (L + 1)) as E2.
  assert (E3 : arrow (L + 1) 2 6 <= arrow (L + 1) 2 (F (L + 1))) by (apply arrow_mono; lia).
  assert (E4 : 2 * arrow (L + 1) 2 5 <= arrow (L + 1) 2 6) by (replace (L + 1) with (S L) by lia; apply arrow_step2).
  assert (E5 : arrow (L + 1) 2 5 = arrow L 2 (F (L + 1))).
  { replace (L + 1) with (S L) by lia. replace 5 with (S 4) by reflexivity. rewrite arrow_SS, <- F_def. reflexivity. }
  assert (E7 : arrow L 2 6 <= arrow L 2 (F (L + 1))) by (apply arrow_mono; lia).
  assert (E8 : 2 * arrow L 2 5 <= arrow L 2 6).
  { destruct L as [| L']; [lia |]. apply arrow_step2. }
  assert (E10 : L + 8 <= arrow L 2 5).
  { pose proof (arrow_mono L 4 5 ltac:(lia)). rewrite <- F_def in H. pose proof (F_ge L). lia. }
  rewrite E1. lia.
Qed.

(** the 0LJ0LC candidate's exact count (BB10_lead_bound.score_exact) is below F^(2 JJ + 1)(34) *)
Lemma lead_lt : 2 * BB10_lead_1RB0RA.b2 + 2 * (4 * BB10_lead_1RB0RA.bf + 33) + 5 < iter (2 * JJ + 1) F 34.
Proof.
  pose proof BB10_lead_bound.b2_closed as Hb2. pose proof BB10_lead_bound.bf_closed as Hbf.
  rewrite arrow_agree in Hb2, Hbf.
  pose proof JJ_ge2 as HJ.
  assert (H3F : F (F (F 34)) <= iter (2 * JJ + 1) F 34) by (apply iter_big; lia).
  revert Hb2 Hbf H3F. generalize BB10_lead_1RB0RA.b2 BB10_lead_1RB0RA.bf. intros b2 bf Hb2 Hbf H3F.
  pose proof (lead_count_lt (4 * bf + 33) ltac:(lia)) as Hl.
  assert (HL : 4 * bf + 35 <= F (F 34)).
  { rewrite arrow_S3 in Hbf. pose proof F34_big. pose proof (F_ge (F 34)). lia. }
  assert (HA : arrow (4 * bf + 33 + 2) 2 4 <= F (F (F 34))).
  { rewrite (F_def (F (F 34))). apply arrow_lvl_le; lia. }
  lia.
Qed.

Theorem beats_lead : exists cl nl co no,
  c0 -[ BB10_lead_1RB0RA.tm ]->* cl /\ halted BB10_lead_1RB0RA.tm cl /\ BB10_lead_bound.ones cl nl /\
  c0 -->* co /\ halted tm co /\ ones co no /\ nl + 1 < no + 1.
Proof.
  destruct BB10_lead_bound.score_exact as [cl [H1 [H2 H3]]].
  destruct score_ge as [co [no [H4 [H5 [H6 H7]]]]].
  exists cl, (2 * BB10_lead_1RB0RA.b2 + 2 * (4 * BB10_lead_1RB0RA.bf + 33) + 5), co, no.
  split; [exact H1 | split; [exact H2 | split; [exact H3 | split; [exact H4 | split; [exact H5 | split; [exact H6 |]]]]]].
  pose proof lead_lt. lia.
Qed.

Theorem beats_champion : exists cc nc co no,
  c0 -[ BB10_champion_1RB1RA.tm ]->* cc /\ halted BB10_champion_1RB1RA.tm cc /\ BB10_champion_bound.ones cc nc /\
  c0 -->* co /\ halted tm co /\ ones co no /\ nc + 1 < no + 1.
Proof.
  destruct BB10_champion_bound.score_exact as [cc [H1 [H2 H3]]].
  destruct score_ge as [co [no [H4 [H5 [H6 H7]]]]].
  exists cc, (BB10_champion_1RB1RA.b2 + 3), co, no.
  split; [exact H1 | split; [exact H2 | split; [exact H3 | split; [exact H4 | split; [exact H5 | split; [exact H6 |]]]]]].
  pose proof BB10_lead_vs_champion.b2c_le. pose proof lead_lt. lia.
Qed.

Print Assumptions score_exact.
Print Assumptions sigma_lower_bound.
Print Assumptions dominates.
Print Assumptions beats_M3_bound.
Print Assumptions beats_lead.
Print Assumptions beats_champion.
